/*
 * GoPlus Security API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.gopluslabs.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gopluslabs.client.model.ERC721Change;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * ERC721BalanceChange
 */



public class ERC721BalanceChange {
  @SerializedName("address")
  private String address = null;

  @SerializedName("erc721_change")
  private List<ERC721Change> erc721Change = null;

  public ERC721BalanceChange address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @Schema(description = "")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public ERC721BalanceChange erc721Change(List<ERC721Change> erc721Change) {
    this.erc721Change = erc721Change;
    return this;
  }

  public ERC721BalanceChange addErc721ChangeItem(ERC721Change erc721ChangeItem) {
    if (this.erc721Change == null) {
      this.erc721Change = new ArrayList<ERC721Change>();
    }
    this.erc721Change.add(erc721ChangeItem);
    return this;
  }

   /**
   * Get erc721Change
   * @return erc721Change
  **/
  @Schema(description = "")
  public List<ERC721Change> getErc721Change() {
    return erc721Change;
  }

  public void setErc721Change(List<ERC721Change> erc721Change) {
    this.erc721Change = erc721Change;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ERC721BalanceChange erC721BalanceChange = (ERC721BalanceChange) o;
    return Objects.equals(this.address, erC721BalanceChange.address) &&
        Objects.equals(this.erc721Change, erC721BalanceChange.erc721Change);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, erc721Change);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ERC721BalanceChange {\n");
    
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    erc721Change: ").append(toIndentedString(erc721Change)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
