/*
 * GoPlus Security API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.gopluslabs.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * NewAllowance
 */



public class NewAllowance {
  @SerializedName("owner")
  private String owner = null;

  @SerializedName("post_amount")
  private String postAmount = null;

  @SerializedName("allowance_change")
  private String allowanceChange = null;

  @SerializedName("spender")
  private String spender = null;

  @SerializedName("risky_spender")
  private Integer riskySpender = null;

  @SerializedName("pre_amount")
  private String preAmount = null;

  public NewAllowance owner(String owner) {
    this.owner = owner;
    return this;
  }

   /**
   * Get owner
   * @return owner
  **/
  @Schema(description = "")
  public String getOwner() {
    return owner;
  }

  public void setOwner(String owner) {
    this.owner = owner;
  }

  public NewAllowance postAmount(String postAmount) {
    this.postAmount = postAmount;
    return this;
  }

   /**
   * Get postAmount
   * @return postAmount
  **/
  @Schema(description = "")
  public String getPostAmount() {
    return postAmount;
  }

  public void setPostAmount(String postAmount) {
    this.postAmount = postAmount;
  }

  public NewAllowance allowanceChange(String allowanceChange) {
    this.allowanceChange = allowanceChange;
    return this;
  }

   /**
   * Get allowanceChange
   * @return allowanceChange
  **/
  @Schema(description = "")
  public String getAllowanceChange() {
    return allowanceChange;
  }

  public void setAllowanceChange(String allowanceChange) {
    this.allowanceChange = allowanceChange;
  }

  public NewAllowance spender(String spender) {
    this.spender = spender;
    return this;
  }

   /**
   * Get spender
   * @return spender
  **/
  @Schema(description = "")
  public String getSpender() {
    return spender;
  }

  public void setSpender(String spender) {
    this.spender = spender;
  }

  public NewAllowance riskySpender(Integer riskySpender) {
    this.riskySpender = riskySpender;
    return this;
  }

   /**
   * Get riskySpender
   * @return riskySpender
  **/
  @Schema(description = "")
  public Integer getRiskySpender() {
    return riskySpender;
  }

  public void setRiskySpender(Integer riskySpender) {
    this.riskySpender = riskySpender;
  }

  public NewAllowance preAmount(String preAmount) {
    this.preAmount = preAmount;
    return this;
  }

   /**
   * Get preAmount
   * @return preAmount
  **/
  @Schema(description = "")
  public String getPreAmount() {
    return preAmount;
  }

  public void setPreAmount(String preAmount) {
    this.preAmount = preAmount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NewAllowance newAllowance = (NewAllowance) o;
    return Objects.equals(this.owner, newAllowance.owner) &&
        Objects.equals(this.postAmount, newAllowance.postAmount) &&
        Objects.equals(this.allowanceChange, newAllowance.allowanceChange) &&
        Objects.equals(this.spender, newAllowance.spender) &&
        Objects.equals(this.riskySpender, newAllowance.riskySpender) &&
        Objects.equals(this.preAmount, newAllowance.preAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(owner, postAmount, allowanceChange, spender, riskySpender, preAmount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NewAllowance {\n");
    
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    postAmount: ").append(toIndentedString(postAmount)).append("\n");
    sb.append("    allowanceChange: ").append(toIndentedString(allowanceChange)).append("\n");
    sb.append("    spender: ").append(toIndentedString(spender)).append("\n");
    sb.append("    riskySpender: ").append(toIndentedString(riskySpender)).append("\n");
    sb.append("    preAmount: ").append(toIndentedString(preAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
