/*
 * GoPlus Security API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.gopluslabs.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gopluslabs.client.model.TaNftLockerLockInfoobject;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * NftLockerResponse
 */



public class NftLockerResponse {
  @SerializedName("list")
  private List<TaNftLockerLockInfoobject> list = null;

  @SerializedName("totalCount")
  private Integer totalCount = null;

  public NftLockerResponse list(List<TaNftLockerLockInfoobject> list) {
    this.list = list;
    return this;
  }

  public NftLockerResponse addListItem(TaNftLockerLockInfoobject listItem) {
    if (this.list == null) {
      this.list = new ArrayList<TaNftLockerLockInfoobject>();
    }
    this.list.add(listItem);
    return this;
  }

   /**
   * Get list
   * @return list
  **/
  @Schema(description = "")
  public List<TaNftLockerLockInfoobject> getList() {
    return list;
  }

  public void setList(List<TaNftLockerLockInfoobject> list) {
    this.list = list;
  }

  public NftLockerResponse totalCount(Integer totalCount) {
    this.totalCount = totalCount;
    return this;
  }

   /**
   * Get totalCount
   * @return totalCount
  **/
  @Schema(description = "")
  public Integer getTotalCount() {
    return totalCount;
  }

  public void setTotalCount(Integer totalCount) {
    this.totalCount = totalCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NftLockerResponse nftLockerResponse = (NftLockerResponse) o;
    return Objects.equals(this.list, nftLockerResponse.list) &&
        Objects.equals(this.totalCount, nftLockerResponse.totalCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(list, totalCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NftLockerResponse {\n");
    
    sb.append("    list: ").append(toIndentedString(list)).append("\n");
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
