/*
 * GoPlus Security API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.gopluslabs.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gopluslabs.client.model.V4NftLockerLockInfos;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * PageResponseV4NftLockerLockInfos
 */



public class PageResponseV4NftLockerLockInfos {
  @SerializedName("list")
  private List<V4NftLockerLockInfos> list = null;

  @SerializedName("pageNum")
  private Integer pageNum = null;

  @SerializedName("pageSize")
  private Integer pageSize = null;

  @SerializedName("totalCount")
  private Integer totalCount = null;

  public PageResponseV4NftLockerLockInfos list(List<V4NftLockerLockInfos> list) {
    this.list = list;
    return this;
  }

  public PageResponseV4NftLockerLockInfos addListItem(V4NftLockerLockInfos listItem) {
    if (this.list == null) {
      this.list = new ArrayList<V4NftLockerLockInfos>();
    }
    this.list.add(listItem);
    return this;
  }

   /**
   * Get list
   * @return list
  **/
  @Schema(description = "")
  public List<V4NftLockerLockInfos> getList() {
    return list;
  }

  public void setList(List<V4NftLockerLockInfos> list) {
    this.list = list;
  }

  public PageResponseV4NftLockerLockInfos pageNum(Integer pageNum) {
    this.pageNum = pageNum;
    return this;
  }

   /**
   * Get pageNum
   * @return pageNum
  **/
  @Schema(description = "")
  public Integer getPageNum() {
    return pageNum;
  }

  public void setPageNum(Integer pageNum) {
    this.pageNum = pageNum;
  }

  public PageResponseV4NftLockerLockInfos pageSize(Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * Get pageSize
   * @return pageSize
  **/
  @Schema(description = "")
  public Integer getPageSize() {
    return pageSize;
  }

  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }

  public PageResponseV4NftLockerLockInfos totalCount(Integer totalCount) {
    this.totalCount = totalCount;
    return this;
  }

   /**
   * Get totalCount
   * @return totalCount
  **/
  @Schema(description = "")
  public Integer getTotalCount() {
    return totalCount;
  }

  public void setTotalCount(Integer totalCount) {
    this.totalCount = totalCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PageResponseV4NftLockerLockInfos pageResponseV4NftLockerLockInfos = (PageResponseV4NftLockerLockInfos) o;
    return Objects.equals(this.list, pageResponseV4NftLockerLockInfos.list) &&
        Objects.equals(this.pageNum, pageResponseV4NftLockerLockInfos.pageNum) &&
        Objects.equals(this.pageSize, pageResponseV4NftLockerLockInfos.pageSize) &&
        Objects.equals(this.totalCount, pageResponseV4NftLockerLockInfos.totalCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(list, pageNum, pageSize, totalCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PageResponseV4NftLockerLockInfos {\n");
    
    sb.append("    list: ").append(toIndentedString(list)).append("\n");
    sb.append("    pageNum: ").append(toIndentedString(pageNum)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
