/*
 * GoPlus Security API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.gopluslabs.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Whetherthe token contract upgradebale. If the contract is upgradable, developers can arbitrarily modify its functions. This field follows the same rules as the other similar fields.
 */
@Schema(description = "Whetherthe token contract upgradebale. If the contract is upgradable, developers can arbitrarily modify its functions. This field follows the same rules as the other similar fields.")


public class ResponseWrapperSuiTokenSecurityContractUpgradeable {
  @SerializedName("cap_owner")
  private String capOwner = null;

  @SerializedName("value")
  private String value = null;

  public ResponseWrapperSuiTokenSecurityContractUpgradeable capOwner(String capOwner) {
    this.capOwner = capOwner;
    return this;
  }

   /**
   * The owner cap of the function. This field can have three possible values: A. A specific address indicates the address that can currently operate this function. B.&#x27;Shared&#x27; means any address can operate this function. C.&#x27;Immutable&#x27; means this function can no longer be invoked.
   * @return capOwner
  **/
  @Schema(description = "The owner cap of the function. This field can have three possible values: A. A specific address indicates the address that can currently operate this function. B.'Shared' means any address can operate this function. C.'Immutable' means this function can no longer be invoked.")
  public String getCapOwner() {
    return capOwner;
  }

  public void setCapOwner(String capOwner) {
    this.capOwner = capOwner;
  }

  public ResponseWrapperSuiTokenSecurityContractUpgradeable value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Status indicator, where \&quot;1\&quot; means the funtcion is available.
   * @return value
  **/
  @Schema(description = "Status indicator, where \"1\" means the funtcion is available.")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseWrapperSuiTokenSecurityContractUpgradeable responseWrapperSuiTokenSecurityContractUpgradeable = (ResponseWrapperSuiTokenSecurityContractUpgradeable) o;
    return Objects.equals(this.capOwner, responseWrapperSuiTokenSecurityContractUpgradeable.capOwner) &&
        Objects.equals(this.value, responseWrapperSuiTokenSecurityContractUpgradeable.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(capOwner, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseWrapperSuiTokenSecurityContractUpgradeable {\n");
    
    sb.append("    capOwner: ").append(toIndentedString(capOwner)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
