/*
 * GoPlus Security API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.gopluslabs.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ResponseWrapperGetNftInfoResultSameNfts
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-07-27T08:37:03.140494914Z[Etc/UTC]")

public class ResponseWrapperGetNftInfoResultSameNfts {
  @SerializedName("nft_address")
  private String nftAddress = null;

  @SerializedName("nft_name")
  private String nftName = null;

  @SerializedName("nft_owner_number")
  private Long nftOwnerNumber = null;

  @SerializedName("create_block_number")
  private Long createBlockNumber = null;

  @SerializedName("nft_symbol")
  private String nftSymbol = null;

  public ResponseWrapperGetNftInfoResultSameNfts nftAddress(String nftAddress) {
    this.nftAddress = nftAddress;
    return this;
  }

   /**
   * It describes the address of the NFTs;
   * @return nftAddress
  **/
  @Schema(description = "It describes the address of the NFTs;")
  public String getNftAddress() {
    return nftAddress;
  }

  public void setNftAddress(String nftAddress) {
    this.nftAddress = nftAddress;
  }

  public ResponseWrapperGetNftInfoResultSameNfts nftName(String nftName) {
    this.nftName = nftName;
    return this;
  }

   /**
   * It describes the name of the NFT;
   * @return nftName
  **/
  @Schema(description = "It describes the name of the NFT;")
  public String getNftName() {
    return nftName;
  }

  public void setNftName(String nftName) {
    this.nftName = nftName;
  }

  public ResponseWrapperGetNftInfoResultSameNfts nftOwnerNumber(Long nftOwnerNumber) {
    this.nftOwnerNumber = nftOwnerNumber;
    return this;
  }

   /**
   * It describes the holders of the NFT;
   * @return nftOwnerNumber
  **/
  @Schema(description = "It describes the holders of the NFT;")
  public Long getNftOwnerNumber() {
    return nftOwnerNumber;
  }

  public void setNftOwnerNumber(Long nftOwnerNumber) {
    this.nftOwnerNumber = nftOwnerNumber;
  }

  public ResponseWrapperGetNftInfoResultSameNfts createBlockNumber(Long createBlockNumber) {
    this.createBlockNumber = createBlockNumber;
    return this;
  }

   /**
   * describes the number of blocks created for the NFT. Return \&quot;null\&quot; means no NFTs with duplicate name and symbol.
   * @return createBlockNumber
  **/
  @Schema(description = "describes the number of blocks created for the NFT. Return \"null\" means no NFTs with duplicate name and symbol.")
  public Long getCreateBlockNumber() {
    return createBlockNumber;
  }

  public void setCreateBlockNumber(Long createBlockNumber) {
    this.createBlockNumber = createBlockNumber;
  }

  public ResponseWrapperGetNftInfoResultSameNfts nftSymbol(String nftSymbol) {
    this.nftSymbol = nftSymbol;
    return this;
  }

   /**
   * It describes the symbol of the NFT;
   * @return nftSymbol
  **/
  @Schema(description = "It describes the symbol of the NFT;")
  public String getNftSymbol() {
    return nftSymbol;
  }

  public void setNftSymbol(String nftSymbol) {
    this.nftSymbol = nftSymbol;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseWrapperGetNftInfoResultSameNfts responseWrapperGetNftInfoResultSameNfts = (ResponseWrapperGetNftInfoResultSameNfts) o;
    return Objects.equals(this.nftAddress, responseWrapperGetNftInfoResultSameNfts.nftAddress) &&
        Objects.equals(this.nftName, responseWrapperGetNftInfoResultSameNfts.nftName) &&
        Objects.equals(this.nftOwnerNumber, responseWrapperGetNftInfoResultSameNfts.nftOwnerNumber) &&
        Objects.equals(this.createBlockNumber, responseWrapperGetNftInfoResultSameNfts.createBlockNumber) &&
        Objects.equals(this.nftSymbol, responseWrapperGetNftInfoResultSameNfts.nftSymbol);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nftAddress, nftName, nftOwnerNumber, createBlockNumber, nftSymbol);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseWrapperGetNftInfoResultSameNfts {\n");
    
    sb.append("    nftAddress: ").append(toIndentedString(nftAddress)).append("\n");
    sb.append("    nftName: ").append(toIndentedString(nftName)).append("\n");
    sb.append("    nftOwnerNumber: ").append(toIndentedString(nftOwnerNumber)).append("\n");
    sb.append("    createBlockNumber: ").append(toIndentedString(createBlockNumber)).append("\n");
    sb.append("    nftSymbol: ").append(toIndentedString(nftSymbol)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
