/*
 * GoPlus Security API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.gopluslabs.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gopluslabs.client.model.ResponseWrapperSuiTokenSecurityBlacklist;
import io.gopluslabs.client.model.ResponseWrapperSuiTokenSecurityContractUpgradeable;
import io.gopluslabs.client.model.ResponseWrapperSuiTokenSecurityMetadataModifiable;
import io.gopluslabs.client.model.ResponseWrapperSuiTokenSecurityMintable;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * key is contract address
 */
@Schema(description = "key is contract address")


public class ResponseWrapperSuiTokenSecurityResult {
  @SerializedName("symbol")
  private String symbol = null;

  @SerializedName("creator")
  private String creator = null;

  @SerializedName("contract_upgradeable")
  private ResponseWrapperSuiTokenSecurityContractUpgradeable contractUpgradeable = null;

  @SerializedName("total_supply")
  private String totalSupply = null;

  @SerializedName("decimals")
  private Integer decimals = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("trusted_token")
  private String trustedToken = null;

  @SerializedName("metadata_modifiable")
  private ResponseWrapperSuiTokenSecurityMetadataModifiable metadataModifiable = null;

  @SerializedName("blacklist")
  private ResponseWrapperSuiTokenSecurityBlacklist blacklist = null;

  @SerializedName("mintable")
  private ResponseWrapperSuiTokenSecurityMintable mintable = null;

  public ResponseWrapperSuiTokenSecurityResult symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Symbol of the token.
   * @return symbol
  **/
  @Schema(description = "Symbol of the token.")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public ResponseWrapperSuiTokenSecurityResult creator(String creator) {
    this.creator = creator;
    return this;
  }

   /**
   * Creator of the token.
   * @return creator
  **/
  @Schema(description = "Creator of the token.")
  public String getCreator() {
    return creator;
  }

  public void setCreator(String creator) {
    this.creator = creator;
  }

  public ResponseWrapperSuiTokenSecurityResult contractUpgradeable(ResponseWrapperSuiTokenSecurityContractUpgradeable contractUpgradeable) {
    this.contractUpgradeable = contractUpgradeable;
    return this;
  }

   /**
   * Get contractUpgradeable
   * @return contractUpgradeable
  **/
  @Schema(description = "")
  public ResponseWrapperSuiTokenSecurityContractUpgradeable getContractUpgradeable() {
    return contractUpgradeable;
  }

  public void setContractUpgradeable(ResponseWrapperSuiTokenSecurityContractUpgradeable contractUpgradeable) {
    this.contractUpgradeable = contractUpgradeable;
  }

  public ResponseWrapperSuiTokenSecurityResult totalSupply(String totalSupply) {
    this.totalSupply = totalSupply;
    return this;
  }

   /**
   * Total supply of the token.
   * @return totalSupply
  **/
  @Schema(description = "Total supply of the token.")
  public String getTotalSupply() {
    return totalSupply;
  }

  public void setTotalSupply(String totalSupply) {
    this.totalSupply = totalSupply;
  }

  public ResponseWrapperSuiTokenSecurityResult decimals(Integer decimals) {
    this.decimals = decimals;
    return this;
  }

   /**
   * Decimals of the token.
   * @return decimals
  **/
  @Schema(description = "Decimals of the token.")
  public Integer getDecimals() {
    return decimals;
  }

  public void setDecimals(Integer decimals) {
    this.decimals = decimals;
  }

  public ResponseWrapperSuiTokenSecurityResult name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the token.
   * @return name
  **/
  @Schema(description = "Name of the token.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ResponseWrapperSuiTokenSecurityResult trustedToken(String trustedToken) {
    this.trustedToken = trustedToken;
    return this;
  }

   /**
   * If the token is a famous and trustworthy one. \&quot;1\&quot; means yes.(Notice: This field is intended to identify well-known and reputable tokens. Trusted tokens with special functions (such as the mintable function in USDC) are generally not considered risk items. Please note that a value other than “1” does not indicate that the token is untrustworthy. We recommend properly evaluating and handling tokens with values other than “1” to avoid unnecessary disputes. )
   * @return trustedToken
  **/
  @Schema(description = "If the token is a famous and trustworthy one. \"1\" means yes.(Notice: This field is intended to identify well-known and reputable tokens. Trusted tokens with special functions (such as the mintable function in USDC) are generally not considered risk items. Please note that a value other than “1” does not indicate that the token is untrustworthy. We recommend properly evaluating and handling tokens with values other than “1” to avoid unnecessary disputes. )")
  public String getTrustedToken() {
    return trustedToken;
  }

  public void setTrustedToken(String trustedToken) {
    this.trustedToken = trustedToken;
  }

  public ResponseWrapperSuiTokenSecurityResult metadataModifiable(ResponseWrapperSuiTokenSecurityMetadataModifiable metadataModifiable) {
    this.metadataModifiable = metadataModifiable;
    return this;
  }

   /**
   * Get metadataModifiable
   * @return metadataModifiable
  **/
  @Schema(description = "")
  public ResponseWrapperSuiTokenSecurityMetadataModifiable getMetadataModifiable() {
    return metadataModifiable;
  }

  public void setMetadataModifiable(ResponseWrapperSuiTokenSecurityMetadataModifiable metadataModifiable) {
    this.metadataModifiable = metadataModifiable;
  }

  public ResponseWrapperSuiTokenSecurityResult blacklist(ResponseWrapperSuiTokenSecurityBlacklist blacklist) {
    this.blacklist = blacklist;
    return this;
  }

   /**
   * Get blacklist
   * @return blacklist
  **/
  @Schema(description = "")
  public ResponseWrapperSuiTokenSecurityBlacklist getBlacklist() {
    return blacklist;
  }

  public void setBlacklist(ResponseWrapperSuiTokenSecurityBlacklist blacklist) {
    this.blacklist = blacklist;
  }

  public ResponseWrapperSuiTokenSecurityResult mintable(ResponseWrapperSuiTokenSecurityMintable mintable) {
    this.mintable = mintable;
    return this;
  }

   /**
   * Get mintable
   * @return mintable
  **/
  @Schema(description = "")
  public ResponseWrapperSuiTokenSecurityMintable getMintable() {
    return mintable;
  }

  public void setMintable(ResponseWrapperSuiTokenSecurityMintable mintable) {
    this.mintable = mintable;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseWrapperSuiTokenSecurityResult responseWrapperSuiTokenSecurityResult = (ResponseWrapperSuiTokenSecurityResult) o;
    return Objects.equals(this.symbol, responseWrapperSuiTokenSecurityResult.symbol) &&
        Objects.equals(this.creator, responseWrapperSuiTokenSecurityResult.creator) &&
        Objects.equals(this.contractUpgradeable, responseWrapperSuiTokenSecurityResult.contractUpgradeable) &&
        Objects.equals(this.totalSupply, responseWrapperSuiTokenSecurityResult.totalSupply) &&
        Objects.equals(this.decimals, responseWrapperSuiTokenSecurityResult.decimals) &&
        Objects.equals(this.name, responseWrapperSuiTokenSecurityResult.name) &&
        Objects.equals(this.trustedToken, responseWrapperSuiTokenSecurityResult.trustedToken) &&
        Objects.equals(this.metadataModifiable, responseWrapperSuiTokenSecurityResult.metadataModifiable) &&
        Objects.equals(this.blacklist, responseWrapperSuiTokenSecurityResult.blacklist) &&
        Objects.equals(this.mintable, responseWrapperSuiTokenSecurityResult.mintable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, creator, contractUpgradeable, totalSupply, decimals, name, trustedToken, metadataModifiable, blacklist, mintable);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseWrapperSuiTokenSecurityResult {\n");
    
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    creator: ").append(toIndentedString(creator)).append("\n");
    sb.append("    contractUpgradeable: ").append(toIndentedString(contractUpgradeable)).append("\n");
    sb.append("    totalSupply: ").append(toIndentedString(totalSupply)).append("\n");
    sb.append("    decimals: ").append(toIndentedString(decimals)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    trustedToken: ").append(toIndentedString(trustedToken)).append("\n");
    sb.append("    metadataModifiable: ").append(toIndentedString(metadataModifiable)).append("\n");
    sb.append("    blacklist: ").append(toIndentedString(blacklist)).append("\n");
    sb.append("    mintable: ").append(toIndentedString(mintable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
