/*
 * GoPlus Security API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.gopluslabs.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ResponseWrapperGetScanResultResultStablecoinDepegRiskDetail
 */



public class ResponseWrapperGetScanResultResultStablecoinDepegRiskDetail {
  @SerializedName("fall_percent")
  private String fallPercent = null;

  @SerializedName("token_address")
  private String tokenAddress = null;

  @SerializedName("token_symbol")
  private String tokenSymbol = null;

  public ResponseWrapperGetScanResultResultStablecoinDepegRiskDetail fallPercent(String fallPercent) {
    this.fallPercent = fallPercent;
    return this;
  }

   /**
   * Get fallPercent
   * @return fallPercent
  **/
  @Schema(description = "")
  public String getFallPercent() {
    return fallPercent;
  }

  public void setFallPercent(String fallPercent) {
    this.fallPercent = fallPercent;
  }

  public ResponseWrapperGetScanResultResultStablecoinDepegRiskDetail tokenAddress(String tokenAddress) {
    this.tokenAddress = tokenAddress;
    return this;
  }

   /**
   * Get tokenAddress
   * @return tokenAddress
  **/
  @Schema(description = "")
  public String getTokenAddress() {
    return tokenAddress;
  }

  public void setTokenAddress(String tokenAddress) {
    this.tokenAddress = tokenAddress;
  }

  public ResponseWrapperGetScanResultResultStablecoinDepegRiskDetail tokenSymbol(String tokenSymbol) {
    this.tokenSymbol = tokenSymbol;
    return this;
  }

   /**
   * Get tokenSymbol
   * @return tokenSymbol
  **/
  @Schema(description = "")
  public String getTokenSymbol() {
    return tokenSymbol;
  }

  public void setTokenSymbol(String tokenSymbol) {
    this.tokenSymbol = tokenSymbol;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseWrapperGetScanResultResultStablecoinDepegRiskDetail responseWrapperGetScanResultResultStablecoinDepegRiskDetail = (ResponseWrapperGetScanResultResultStablecoinDepegRiskDetail) o;
    return Objects.equals(this.fallPercent, responseWrapperGetScanResultResultStablecoinDepegRiskDetail.fallPercent) &&
        Objects.equals(this.tokenAddress, responseWrapperGetScanResultResultStablecoinDepegRiskDetail.tokenAddress) &&
        Objects.equals(this.tokenSymbol, responseWrapperGetScanResultResultStablecoinDepegRiskDetail.tokenSymbol);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fallPercent, tokenAddress, tokenSymbol);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseWrapperGetScanResultResultStablecoinDepegRiskDetail {\n");
    
    sb.append("    fallPercent: ").append(toIndentedString(fallPercent)).append("\n");
    sb.append("    tokenAddress: ").append(toIndentedString(tokenAddress)).append("\n");
    sb.append("    tokenSymbol: ").append(toIndentedString(tokenSymbol)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
