/*
 * GoPlus Security API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.gopluslabs.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gopluslabs.client.model.ResponseWrapperGetScanResultResultAddressPoisoned;
import io.gopluslabs.client.model.ResponseWrapperGetScanResultResultApprovalRisk;
import io.gopluslabs.client.model.ResponseWrapperGetScanResultResultStablecoinDepeg;
import io.gopluslabs.client.model.ResponseWrapperGetScanResultResultTokenAttention;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Response result
 */
@Schema(description = "Response result")


public class ResponseWrapperGetScanResultResult {
  @SerializedName("chain_id")
  private String chainId = null;

  @SerializedName("approval_risk")
  private ResponseWrapperGetScanResultResultApprovalRisk approvalRisk = null;

  @SerializedName("token_attention")
  private ResponseWrapperGetScanResultResultTokenAttention tokenAttention = null;

  @SerializedName("nft_attention")
  private ResponseWrapperGetScanResultResultTokenAttention nftAttention = null;

  @SerializedName("stablecoin_depeg")
  private ResponseWrapperGetScanResultResultStablecoinDepeg stablecoinDepeg = null;

  @SerializedName("address_poisoned")
  private ResponseWrapperGetScanResultResultAddressPoisoned addressPoisoned = null;

  @SerializedName("excessive_gas_fee")
  private ResponseWrapperGetScanResultResultAddressPoisoned excessiveGasFee = null;

  @SerializedName("nft_risk")
  private ResponseWrapperGetScanResultResultTokenAttention nftRisk = null;

  @SerializedName("nft_stolen")
  private ResponseWrapperGetScanResultResultAddressPoisoned nftStolen = null;

  @SerializedName("scan_time")
  private String scanTime = null;

  @SerializedName("request_id")
  private String requestId = null;

  @SerializedName("token_risk")
  private ResponseWrapperGetScanResultResultTokenAttention tokenRisk = null;

  @SerializedName("risky_address_interaction")
  private ResponseWrapperGetScanResultResultAddressPoisoned riskyAddressInteraction = null;

  public ResponseWrapperGetScanResultResult chainId(String chainId) {
    this.chainId = chainId;
    return this;
  }

   /**
   * Chain ID
   * @return chainId
  **/
  @Schema(description = "Chain ID")
  public String getChainId() {
    return chainId;
  }

  public void setChainId(String chainId) {
    this.chainId = chainId;
  }

  public ResponseWrapperGetScanResultResult approvalRisk(ResponseWrapperGetScanResultResultApprovalRisk approvalRisk) {
    this.approvalRisk = approvalRisk;
    return this;
  }

   /**
   * Get approvalRisk
   * @return approvalRisk
  **/
  @Schema(description = "")
  public ResponseWrapperGetScanResultResultApprovalRisk getApprovalRisk() {
    return approvalRisk;
  }

  public void setApprovalRisk(ResponseWrapperGetScanResultResultApprovalRisk approvalRisk) {
    this.approvalRisk = approvalRisk;
  }

  public ResponseWrapperGetScanResultResult tokenAttention(ResponseWrapperGetScanResultResultTokenAttention tokenAttention) {
    this.tokenAttention = tokenAttention;
    return this;
  }

   /**
   * Get tokenAttention
   * @return tokenAttention
  **/
  @Schema(description = "")
  public ResponseWrapperGetScanResultResultTokenAttention getTokenAttention() {
    return tokenAttention;
  }

  public void setTokenAttention(ResponseWrapperGetScanResultResultTokenAttention tokenAttention) {
    this.tokenAttention = tokenAttention;
  }

  public ResponseWrapperGetScanResultResult nftAttention(ResponseWrapperGetScanResultResultTokenAttention nftAttention) {
    this.nftAttention = nftAttention;
    return this;
  }

   /**
   * Get nftAttention
   * @return nftAttention
  **/
  @Schema(description = "")
  public ResponseWrapperGetScanResultResultTokenAttention getNftAttention() {
    return nftAttention;
  }

  public void setNftAttention(ResponseWrapperGetScanResultResultTokenAttention nftAttention) {
    this.nftAttention = nftAttention;
  }

  public ResponseWrapperGetScanResultResult stablecoinDepeg(ResponseWrapperGetScanResultResultStablecoinDepeg stablecoinDepeg) {
    this.stablecoinDepeg = stablecoinDepeg;
    return this;
  }

   /**
   * Get stablecoinDepeg
   * @return stablecoinDepeg
  **/
  @Schema(description = "")
  public ResponseWrapperGetScanResultResultStablecoinDepeg getStablecoinDepeg() {
    return stablecoinDepeg;
  }

  public void setStablecoinDepeg(ResponseWrapperGetScanResultResultStablecoinDepeg stablecoinDepeg) {
    this.stablecoinDepeg = stablecoinDepeg;
  }

  public ResponseWrapperGetScanResultResult addressPoisoned(ResponseWrapperGetScanResultResultAddressPoisoned addressPoisoned) {
    this.addressPoisoned = addressPoisoned;
    return this;
  }

   /**
   * Get addressPoisoned
   * @return addressPoisoned
  **/
  @Schema(description = "")
  public ResponseWrapperGetScanResultResultAddressPoisoned getAddressPoisoned() {
    return addressPoisoned;
  }

  public void setAddressPoisoned(ResponseWrapperGetScanResultResultAddressPoisoned addressPoisoned) {
    this.addressPoisoned = addressPoisoned;
  }

  public ResponseWrapperGetScanResultResult excessiveGasFee(ResponseWrapperGetScanResultResultAddressPoisoned excessiveGasFee) {
    this.excessiveGasFee = excessiveGasFee;
    return this;
  }

   /**
   * Get excessiveGasFee
   * @return excessiveGasFee
  **/
  @Schema(description = "")
  public ResponseWrapperGetScanResultResultAddressPoisoned getExcessiveGasFee() {
    return excessiveGasFee;
  }

  public void setExcessiveGasFee(ResponseWrapperGetScanResultResultAddressPoisoned excessiveGasFee) {
    this.excessiveGasFee = excessiveGasFee;
  }

  public ResponseWrapperGetScanResultResult nftRisk(ResponseWrapperGetScanResultResultTokenAttention nftRisk) {
    this.nftRisk = nftRisk;
    return this;
  }

   /**
   * Get nftRisk
   * @return nftRisk
  **/
  @Schema(description = "")
  public ResponseWrapperGetScanResultResultTokenAttention getNftRisk() {
    return nftRisk;
  }

  public void setNftRisk(ResponseWrapperGetScanResultResultTokenAttention nftRisk) {
    this.nftRisk = nftRisk;
  }

  public ResponseWrapperGetScanResultResult nftStolen(ResponseWrapperGetScanResultResultAddressPoisoned nftStolen) {
    this.nftStolen = nftStolen;
    return this;
  }

   /**
   * Get nftStolen
   * @return nftStolen
  **/
  @Schema(description = "")
  public ResponseWrapperGetScanResultResultAddressPoisoned getNftStolen() {
    return nftStolen;
  }

  public void setNftStolen(ResponseWrapperGetScanResultResultAddressPoisoned nftStolen) {
    this.nftStolen = nftStolen;
  }

  public ResponseWrapperGetScanResultResult scanTime(String scanTime) {
    this.scanTime = scanTime;
    return this;
  }

   /**
   * Scan initiation time. UTC+0.
   * @return scanTime
  **/
  @Schema(description = "Scan initiation time. UTC+0.")
  public String getScanTime() {
    return scanTime;
  }

  public void setScanTime(String scanTime) {
    this.scanTime = scanTime;
  }

  public ResponseWrapperGetScanResultResult requestId(String requestId) {
    this.requestId = requestId;
    return this;
  }

   /**
   * Request ID
   * @return requestId
  **/
  @Schema(description = "Request ID")
  public String getRequestId() {
    return requestId;
  }

  public void setRequestId(String requestId) {
    this.requestId = requestId;
  }

  public ResponseWrapperGetScanResultResult tokenRisk(ResponseWrapperGetScanResultResultTokenAttention tokenRisk) {
    this.tokenRisk = tokenRisk;
    return this;
  }

   /**
   * Get tokenRisk
   * @return tokenRisk
  **/
  @Schema(description = "")
  public ResponseWrapperGetScanResultResultTokenAttention getTokenRisk() {
    return tokenRisk;
  }

  public void setTokenRisk(ResponseWrapperGetScanResultResultTokenAttention tokenRisk) {
    this.tokenRisk = tokenRisk;
  }

  public ResponseWrapperGetScanResultResult riskyAddressInteraction(ResponseWrapperGetScanResultResultAddressPoisoned riskyAddressInteraction) {
    this.riskyAddressInteraction = riskyAddressInteraction;
    return this;
  }

   /**
   * Get riskyAddressInteraction
   * @return riskyAddressInteraction
  **/
  @Schema(description = "")
  public ResponseWrapperGetScanResultResultAddressPoisoned getRiskyAddressInteraction() {
    return riskyAddressInteraction;
  }

  public void setRiskyAddressInteraction(ResponseWrapperGetScanResultResultAddressPoisoned riskyAddressInteraction) {
    this.riskyAddressInteraction = riskyAddressInteraction;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseWrapperGetScanResultResult responseWrapperGetScanResultResult = (ResponseWrapperGetScanResultResult) o;
    return Objects.equals(this.chainId, responseWrapperGetScanResultResult.chainId) &&
        Objects.equals(this.approvalRisk, responseWrapperGetScanResultResult.approvalRisk) &&
        Objects.equals(this.tokenAttention, responseWrapperGetScanResultResult.tokenAttention) &&
        Objects.equals(this.nftAttention, responseWrapperGetScanResultResult.nftAttention) &&
        Objects.equals(this.stablecoinDepeg, responseWrapperGetScanResultResult.stablecoinDepeg) &&
        Objects.equals(this.addressPoisoned, responseWrapperGetScanResultResult.addressPoisoned) &&
        Objects.equals(this.excessiveGasFee, responseWrapperGetScanResultResult.excessiveGasFee) &&
        Objects.equals(this.nftRisk, responseWrapperGetScanResultResult.nftRisk) &&
        Objects.equals(this.nftStolen, responseWrapperGetScanResultResult.nftStolen) &&
        Objects.equals(this.scanTime, responseWrapperGetScanResultResult.scanTime) &&
        Objects.equals(this.requestId, responseWrapperGetScanResultResult.requestId) &&
        Objects.equals(this.tokenRisk, responseWrapperGetScanResultResult.tokenRisk) &&
        Objects.equals(this.riskyAddressInteraction, responseWrapperGetScanResultResult.riskyAddressInteraction);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chainId, approvalRisk, tokenAttention, nftAttention, stablecoinDepeg, addressPoisoned, excessiveGasFee, nftRisk, nftStolen, scanTime, requestId, tokenRisk, riskyAddressInteraction);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseWrapperGetScanResultResult {\n");
    
    sb.append("    chainId: ").append(toIndentedString(chainId)).append("\n");
    sb.append("    approvalRisk: ").append(toIndentedString(approvalRisk)).append("\n");
    sb.append("    tokenAttention: ").append(toIndentedString(tokenAttention)).append("\n");
    sb.append("    nftAttention: ").append(toIndentedString(nftAttention)).append("\n");
    sb.append("    stablecoinDepeg: ").append(toIndentedString(stablecoinDepeg)).append("\n");
    sb.append("    addressPoisoned: ").append(toIndentedString(addressPoisoned)).append("\n");
    sb.append("    excessiveGasFee: ").append(toIndentedString(excessiveGasFee)).append("\n");
    sb.append("    nftRisk: ").append(toIndentedString(nftRisk)).append("\n");
    sb.append("    nftStolen: ").append(toIndentedString(nftStolen)).append("\n");
    sb.append("    scanTime: ").append(toIndentedString(scanTime)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    tokenRisk: ").append(toIndentedString(tokenRisk)).append("\n");
    sb.append("    riskyAddressInteraction: ").append(toIndentedString(riskyAddressInteraction)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
