/*
 * GoPlus Security API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.gopluslabs.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gopluslabs.client.model.ResponseWrapperGetDefiInfoResultOwner;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Response result
 */
@Schema(description = "Response result")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-02T06:35:16.334290770Z[Etc/UTC]")
public class ResponseWrapperGetDefiInfoResult {
  @SerializedName("owner")
  private ResponseWrapperGetDefiInfoResultOwner owner = null;

  @SerializedName("privilege_withdraw")
  private Integer privilegeWithdraw = null;

  @SerializedName("withdraw_missing")
  private Integer withdrawMissing = null;

  @SerializedName("is_open_source")
  private Integer isOpenSource = null;

  @SerializedName("blacklist")
  private Integer blacklist = null;

  @SerializedName("contract_name")
  private String contractName = null;

  @SerializedName("selfdestruct")
  private Integer selfdestruct = null;

  @SerializedName("is_proxy")
  private Integer isProxy = null;

  @SerializedName("approval_abuse")
  private Integer approvalAbuse = null;

  public ResponseWrapperGetDefiInfoResult owner(ResponseWrapperGetDefiInfoResultOwner owner) {
    this.owner = owner;
    return this;
  }

   /**
   * Get owner
   * @return owner
  **/
  @Schema(description = "")
  public ResponseWrapperGetDefiInfoResultOwner getOwner() {
    return owner;
  }

  public void setOwner(ResponseWrapperGetDefiInfoResultOwner owner) {
    this.owner = owner;
  }

  public ResponseWrapperGetDefiInfoResult privilegeWithdraw(Integer privilegeWithdraw) {
    this.privilegeWithdraw = privilegeWithdraw;
    return this;
  }

   /**
   * It descirbes whether the contract owner can withdraw all the assets in the contract, without uses&#x27; permission. \&quot;1\&quot; means true; \&quot;0\&quot; means false;  \&quot;-1\&quot; means unknown.
   * @return privilegeWithdraw
  **/
  @Schema(description = "It descirbes whether the contract owner can withdraw all the assets in the contract, without uses' permission. \"1\" means true; \"0\" means false;  \"-1\" means unknown.")
  public Integer getPrivilegeWithdraw() {
    return privilegeWithdraw;
  }

  public void setPrivilegeWithdraw(Integer privilegeWithdraw) {
    this.privilegeWithdraw = privilegeWithdraw;
  }

  public ResponseWrapperGetDefiInfoResult withdrawMissing(Integer withdrawMissing) {
    this.withdrawMissing = withdrawMissing;
    return this;
  }

   /**
   * It describes whether the contract lacks withdrawal method. If it is missing, users will be unable to withdraw the assets they have putted in. \&quot;1\&quot; means true; \&quot;0\&quot; means false;  \&quot;-1\&quot; means unknown.
   * @return withdrawMissing
  **/
  @Schema(description = "It describes whether the contract lacks withdrawal method. If it is missing, users will be unable to withdraw the assets they have putted in. \"1\" means true; \"0\" means false;  \"-1\" means unknown.")
  public Integer getWithdrawMissing() {
    return withdrawMissing;
  }

  public void setWithdrawMissing(Integer withdrawMissing) {
    this.withdrawMissing = withdrawMissing;
  }

  public ResponseWrapperGetDefiInfoResult isOpenSource(Integer isOpenSource) {
    this.isOpenSource = isOpenSource;
    return this;
  }

   /**
   * It describes whether this contract is open source.  \&quot;1\&quot; means true;  \&quot;0\&quot; means false.
   * @return isOpenSource
  **/
  @Schema(description = "It describes whether this contract is open source.  \"1\" means true;  \"0\" means false.")
  public Integer getIsOpenSource() {
    return isOpenSource;
  }

  public void setIsOpenSource(Integer isOpenSource) {
    this.isOpenSource = isOpenSource;
  }

  public ResponseWrapperGetDefiInfoResult blacklist(Integer blacklist) {
    this.blacklist = blacklist;
    return this;
  }

   /**
   * It describes whether the contract has blacklist function that would block user from withdrawing their assets. \&quot;1\&quot; means true; \&quot;0\&quot; means false;  \&quot;-1\&quot; means unknown.
   * @return blacklist
  **/
  @Schema(description = "It describes whether the contract has blacklist function that would block user from withdrawing their assets. \"1\" means true; \"0\" means false;  \"-1\" means unknown.")
  public Integer getBlacklist() {
    return blacklist;
  }

  public void setBlacklist(Integer blacklist) {
    this.blacklist = blacklist;
  }

  public ResponseWrapperGetDefiInfoResult contractName(String contractName) {
    this.contractName = contractName;
    return this;
  }

   /**
   * Name of the contract.
   * @return contractName
  **/
  @Schema(description = "Name of the contract.")
  public String getContractName() {
    return contractName;
  }

  public void setContractName(String contractName) {
    this.contractName = contractName;
  }

  public ResponseWrapperGetDefiInfoResult selfdestruct(Integer selfdestruct) {
    this.selfdestruct = selfdestruct;
    return this;
  }

   /**
   * It describes whether this contract can self destruct. \&quot;1\&quot; means true;  \&quot;0\&quot; means false; “-1” means unknown.
   * @return selfdestruct
  **/
  @Schema(description = "It describes whether this contract can self destruct. \"1\" means true;  \"0\" means false; “-1” means unknown.")
  public Integer getSelfdestruct() {
    return selfdestruct;
  }

  public void setSelfdestruct(Integer selfdestruct) {
    this.selfdestruct = selfdestruct;
  }

  public ResponseWrapperGetDefiInfoResult isProxy(Integer isProxy) {
    this.isProxy = isProxy;
    return this;
  }

   /**
   * It describes whether this contract has a proxy contract.  \&quot;1\&quot; means true;  \&quot;0\&quot; means false; “-1” means unknown.
   * @return isProxy
  **/
  @Schema(description = "It describes whether this contract has a proxy contract.  \"1\" means true;  \"0\" means false; “-1” means unknown.")
  public Integer getIsProxy() {
    return isProxy;
  }

  public void setIsProxy(Integer isProxy) {
    this.isProxy = isProxy;
  }

  public ResponseWrapperGetDefiInfoResult approvalAbuse(Integer approvalAbuse) {
    this.approvalAbuse = approvalAbuse;
    return this;
  }

   /**
   * It describes whether the owner can spend the allowance that obtained by the contract. If so, this function could potentially be abused to steal user assets. \&quot;1\&quot; means true;  \&quot;0\&quot; means false; “-1” means unknown.
   * @return approvalAbuse
  **/
  @Schema(description = "It describes whether the owner can spend the allowance that obtained by the contract. If so, this function could potentially be abused to steal user assets. \"1\" means true;  \"0\" means false; “-1” means unknown.")
  public Integer getApprovalAbuse() {
    return approvalAbuse;
  }

  public void setApprovalAbuse(Integer approvalAbuse) {
    this.approvalAbuse = approvalAbuse;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseWrapperGetDefiInfoResult responseWrapperGetDefiInfoResult = (ResponseWrapperGetDefiInfoResult) o;
    return Objects.equals(this.owner, responseWrapperGetDefiInfoResult.owner) &&
        Objects.equals(this.privilegeWithdraw, responseWrapperGetDefiInfoResult.privilegeWithdraw) &&
        Objects.equals(this.withdrawMissing, responseWrapperGetDefiInfoResult.withdrawMissing) &&
        Objects.equals(this.isOpenSource, responseWrapperGetDefiInfoResult.isOpenSource) &&
        Objects.equals(this.blacklist, responseWrapperGetDefiInfoResult.blacklist) &&
        Objects.equals(this.contractName, responseWrapperGetDefiInfoResult.contractName) &&
        Objects.equals(this.selfdestruct, responseWrapperGetDefiInfoResult.selfdestruct) &&
        Objects.equals(this.isProxy, responseWrapperGetDefiInfoResult.isProxy) &&
        Objects.equals(this.approvalAbuse, responseWrapperGetDefiInfoResult.approvalAbuse);
  }

  @Override
  public int hashCode() {
    return Objects.hash(owner, privilegeWithdraw, withdrawMissing, isOpenSource, blacklist, contractName, selfdestruct, isProxy, approvalAbuse);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseWrapperGetDefiInfoResult {\n");
    
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    privilegeWithdraw: ").append(toIndentedString(privilegeWithdraw)).append("\n");
    sb.append("    withdrawMissing: ").append(toIndentedString(withdrawMissing)).append("\n");
    sb.append("    isOpenSource: ").append(toIndentedString(isOpenSource)).append("\n");
    sb.append("    blacklist: ").append(toIndentedString(blacklist)).append("\n");
    sb.append("    contractName: ").append(toIndentedString(contractName)).append("\n");
    sb.append("    selfdestruct: ").append(toIndentedString(selfdestruct)).append("\n");
    sb.append("    isProxy: ").append(toIndentedString(isProxy)).append("\n");
    sb.append("    approvalAbuse: ").append(toIndentedString(approvalAbuse)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
