/*
 * GoPlus Security API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.gopluslabs.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gopluslabs.client.model.ResponseWrapperGetScanResultResultApprovalRiskErc20Risk;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * ResponseWrapperGetScanResultResultApprovalRiskRiskDetail
 */



public class ResponseWrapperGetScanResultResultApprovalRiskRiskDetail {
  @SerializedName("erc20_risk")
  private List<ResponseWrapperGetScanResultResultApprovalRiskErc20Risk> erc20Risk = null;

  public ResponseWrapperGetScanResultResultApprovalRiskRiskDetail erc20Risk(List<ResponseWrapperGetScanResultResultApprovalRiskErc20Risk> erc20Risk) {
    this.erc20Risk = erc20Risk;
    return this;
  }

  public ResponseWrapperGetScanResultResultApprovalRiskRiskDetail addErc20RiskItem(ResponseWrapperGetScanResultResultApprovalRiskErc20Risk erc20RiskItem) {
    if (this.erc20Risk == null) {
      this.erc20Risk = new ArrayList<ResponseWrapperGetScanResultResultApprovalRiskErc20Risk>();
    }
    this.erc20Risk.add(erc20RiskItem);
    return this;
  }

   /**
   * Get erc20Risk
   * @return erc20Risk
  **/
  @Schema(description = "")
  public List<ResponseWrapperGetScanResultResultApprovalRiskErc20Risk> getErc20Risk() {
    return erc20Risk;
  }

  public void setErc20Risk(List<ResponseWrapperGetScanResultResultApprovalRiskErc20Risk> erc20Risk) {
    this.erc20Risk = erc20Risk;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseWrapperGetScanResultResultApprovalRiskRiskDetail responseWrapperGetScanResultResultApprovalRiskRiskDetail = (ResponseWrapperGetScanResultResultApprovalRiskRiskDetail) o;
    return Objects.equals(this.erc20Risk, responseWrapperGetScanResultResultApprovalRiskRiskDetail.erc20Risk);
  }

  @Override
  public int hashCode() {
    return Objects.hash(erc20Risk);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseWrapperGetScanResultResultApprovalRiskRiskDetail {\n");
    
    sb.append("    erc20Risk: ").append(toIndentedString(erc20Risk)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
