/*
 * GoPlus Security API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.gopluslabs.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Response result
 */
@Schema(description = "Response result")


public class ResponseWrapperDustAttackDetectionResult {
  @SerializedName("attack_hash")
  private String attackHash = null;

  @SerializedName("is_under_attack")
  private String isUnderAttack = null;

  public ResponseWrapperDustAttackDetectionResult attackHash(String attackHash) {
    this.attackHash = attackHash;
    return this;
  }

   /**
   * 0/1
   * @return attackHash
  **/
  @Schema(description = "0/1")
  public String getAttackHash() {
    return attackHash;
  }

  public void setAttackHash(String attackHash) {
    this.attackHash = attackHash;
  }

  public ResponseWrapperDustAttackDetectionResult isUnderAttack(String isUnderAttack) {
    this.isUnderAttack = isUnderAttack;
    return this;
  }

   /**
   * 0/1
   * @return isUnderAttack
  **/
  @Schema(description = "0/1")
  public String getIsUnderAttack() {
    return isUnderAttack;
  }

  public void setIsUnderAttack(String isUnderAttack) {
    this.isUnderAttack = isUnderAttack;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseWrapperDustAttackDetectionResult responseWrapperDustAttackDetectionResult = (ResponseWrapperDustAttackDetectionResult) o;
    return Objects.equals(this.attackHash, responseWrapperDustAttackDetectionResult.attackHash) &&
        Objects.equals(this.isUnderAttack, responseWrapperDustAttackDetectionResult.isUnderAttack);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attackHash, isUnderAttack);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseWrapperDustAttackDetectionResult {\n");
    
    sb.append("    attackHash: ").append(toIndentedString(attackHash)).append("\n");
    sb.append("    isUnderAttack: ").append(toIndentedString(isUnderAttack)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
