/*
 * GoPlus Security API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.gopluslabs.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gopluslabs.client.model.ResponseWrapperTokenSecurityB20TokenB20InfoBlacklist;
import io.gopluslabs.client.model.ResponseWrapperTokenSecurityB20TokenB20InfoCannotBuy;
import io.gopluslabs.client.model.ResponseWrapperTokenSecurityB20TokenB20InfoCannotSell;
import io.gopluslabs.client.model.ResponseWrapperTokenSecurityB20TokenB20InfoMetadataModifiable;
import io.gopluslabs.client.model.ResponseWrapperTokenSecurityB20TokenB20InfoMintable;
import io.gopluslabs.client.model.ResponseWrapperTokenSecurityB20TokenB20InfoOwnerChangeBalance;
import io.gopluslabs.client.model.ResponseWrapperTokenSecurityB20TokenB20InfoTransferPausable;
import io.gopluslabs.client.model.ResponseWrapperTokenSecurityB20TokenB20InfoWhitelist;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * It describes the detailed B20 token permission information.
 */
@Schema(description = "It describes the detailed B20 token permission information.")


public class ResponseWrapperTokenSecurityB20TokenB20Info {
  @SerializedName("transfer_pausable")
  private ResponseWrapperTokenSecurityB20TokenB20InfoTransferPausable transferPausable = null;

  @SerializedName("owner_change_balance")
  private ResponseWrapperTokenSecurityB20TokenB20InfoOwnerChangeBalance ownerChangeBalance = null;

  @SerializedName("cannot_buy")
  private ResponseWrapperTokenSecurityB20TokenB20InfoCannotBuy cannotBuy = null;

  @SerializedName("metadata_modifiable")
  private ResponseWrapperTokenSecurityB20TokenB20InfoMetadataModifiable metadataModifiable = null;

  @SerializedName("blacklist")
  private ResponseWrapperTokenSecurityB20TokenB20InfoBlacklist blacklist = null;

  @SerializedName("cannot_sell")
  private ResponseWrapperTokenSecurityB20TokenB20InfoCannotSell cannotSell = null;

  @SerializedName("whitelist")
  private ResponseWrapperTokenSecurityB20TokenB20InfoWhitelist whitelist = null;

  @SerializedName("mintable")
  private ResponseWrapperTokenSecurityB20TokenB20InfoMintable mintable = null;

  public ResponseWrapperTokenSecurityB20TokenB20Info transferPausable(ResponseWrapperTokenSecurityB20TokenB20InfoTransferPausable transferPausable) {
    this.transferPausable = transferPausable;
    return this;
  }

   /**
   * Get transferPausable
   * @return transferPausable
  **/
  @Schema(description = "")
  public ResponseWrapperTokenSecurityB20TokenB20InfoTransferPausable getTransferPausable() {
    return transferPausable;
  }

  public void setTransferPausable(ResponseWrapperTokenSecurityB20TokenB20InfoTransferPausable transferPausable) {
    this.transferPausable = transferPausable;
  }

  public ResponseWrapperTokenSecurityB20TokenB20Info ownerChangeBalance(ResponseWrapperTokenSecurityB20TokenB20InfoOwnerChangeBalance ownerChangeBalance) {
    this.ownerChangeBalance = ownerChangeBalance;
    return this;
  }

   /**
   * Get ownerChangeBalance
   * @return ownerChangeBalance
  **/
  @Schema(description = "")
  public ResponseWrapperTokenSecurityB20TokenB20InfoOwnerChangeBalance getOwnerChangeBalance() {
    return ownerChangeBalance;
  }

  public void setOwnerChangeBalance(ResponseWrapperTokenSecurityB20TokenB20InfoOwnerChangeBalance ownerChangeBalance) {
    this.ownerChangeBalance = ownerChangeBalance;
  }

  public ResponseWrapperTokenSecurityB20TokenB20Info cannotBuy(ResponseWrapperTokenSecurityB20TokenB20InfoCannotBuy cannotBuy) {
    this.cannotBuy = cannotBuy;
    return this;
  }

   /**
   * Get cannotBuy
   * @return cannotBuy
  **/
  @Schema(description = "")
  public ResponseWrapperTokenSecurityB20TokenB20InfoCannotBuy getCannotBuy() {
    return cannotBuy;
  }

  public void setCannotBuy(ResponseWrapperTokenSecurityB20TokenB20InfoCannotBuy cannotBuy) {
    this.cannotBuy = cannotBuy;
  }

  public ResponseWrapperTokenSecurityB20TokenB20Info metadataModifiable(ResponseWrapperTokenSecurityB20TokenB20InfoMetadataModifiable metadataModifiable) {
    this.metadataModifiable = metadataModifiable;
    return this;
  }

   /**
   * Get metadataModifiable
   * @return metadataModifiable
  **/
  @Schema(description = "")
  public ResponseWrapperTokenSecurityB20TokenB20InfoMetadataModifiable getMetadataModifiable() {
    return metadataModifiable;
  }

  public void setMetadataModifiable(ResponseWrapperTokenSecurityB20TokenB20InfoMetadataModifiable metadataModifiable) {
    this.metadataModifiable = metadataModifiable;
  }

  public ResponseWrapperTokenSecurityB20TokenB20Info blacklist(ResponseWrapperTokenSecurityB20TokenB20InfoBlacklist blacklist) {
    this.blacklist = blacklist;
    return this;
  }

   /**
   * Get blacklist
   * @return blacklist
  **/
  @Schema(description = "")
  public ResponseWrapperTokenSecurityB20TokenB20InfoBlacklist getBlacklist() {
    return blacklist;
  }

  public void setBlacklist(ResponseWrapperTokenSecurityB20TokenB20InfoBlacklist blacklist) {
    this.blacklist = blacklist;
  }

  public ResponseWrapperTokenSecurityB20TokenB20Info cannotSell(ResponseWrapperTokenSecurityB20TokenB20InfoCannotSell cannotSell) {
    this.cannotSell = cannotSell;
    return this;
  }

   /**
   * Get cannotSell
   * @return cannotSell
  **/
  @Schema(description = "")
  public ResponseWrapperTokenSecurityB20TokenB20InfoCannotSell getCannotSell() {
    return cannotSell;
  }

  public void setCannotSell(ResponseWrapperTokenSecurityB20TokenB20InfoCannotSell cannotSell) {
    this.cannotSell = cannotSell;
  }

  public ResponseWrapperTokenSecurityB20TokenB20Info whitelist(ResponseWrapperTokenSecurityB20TokenB20InfoWhitelist whitelist) {
    this.whitelist = whitelist;
    return this;
  }

   /**
   * Get whitelist
   * @return whitelist
  **/
  @Schema(description = "")
  public ResponseWrapperTokenSecurityB20TokenB20InfoWhitelist getWhitelist() {
    return whitelist;
  }

  public void setWhitelist(ResponseWrapperTokenSecurityB20TokenB20InfoWhitelist whitelist) {
    this.whitelist = whitelist;
  }

  public ResponseWrapperTokenSecurityB20TokenB20Info mintable(ResponseWrapperTokenSecurityB20TokenB20InfoMintable mintable) {
    this.mintable = mintable;
    return this;
  }

   /**
   * Get mintable
   * @return mintable
  **/
  @Schema(description = "")
  public ResponseWrapperTokenSecurityB20TokenB20InfoMintable getMintable() {
    return mintable;
  }

  public void setMintable(ResponseWrapperTokenSecurityB20TokenB20InfoMintable mintable) {
    this.mintable = mintable;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseWrapperTokenSecurityB20TokenB20Info responseWrapperTokenSecurityB20TokenB20Info = (ResponseWrapperTokenSecurityB20TokenB20Info) o;
    return Objects.equals(this.transferPausable, responseWrapperTokenSecurityB20TokenB20Info.transferPausable) &&
        Objects.equals(this.ownerChangeBalance, responseWrapperTokenSecurityB20TokenB20Info.ownerChangeBalance) &&
        Objects.equals(this.cannotBuy, responseWrapperTokenSecurityB20TokenB20Info.cannotBuy) &&
        Objects.equals(this.metadataModifiable, responseWrapperTokenSecurityB20TokenB20Info.metadataModifiable) &&
        Objects.equals(this.blacklist, responseWrapperTokenSecurityB20TokenB20Info.blacklist) &&
        Objects.equals(this.cannotSell, responseWrapperTokenSecurityB20TokenB20Info.cannotSell) &&
        Objects.equals(this.whitelist, responseWrapperTokenSecurityB20TokenB20Info.whitelist) &&
        Objects.equals(this.mintable, responseWrapperTokenSecurityB20TokenB20Info.mintable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transferPausable, ownerChangeBalance, cannotBuy, metadataModifiable, blacklist, cannotSell, whitelist, mintable);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseWrapperTokenSecurityB20TokenB20Info {\n");
    
    sb.append("    transferPausable: ").append(toIndentedString(transferPausable)).append("\n");
    sb.append("    ownerChangeBalance: ").append(toIndentedString(ownerChangeBalance)).append("\n");
    sb.append("    cannotBuy: ").append(toIndentedString(cannotBuy)).append("\n");
    sb.append("    metadataModifiable: ").append(toIndentedString(metadataModifiable)).append("\n");
    sb.append("    blacklist: ").append(toIndentedString(blacklist)).append("\n");
    sb.append("    cannotSell: ").append(toIndentedString(cannotSell)).append("\n");
    sb.append("    whitelist: ").append(toIndentedString(whitelist)).append("\n");
    sb.append("    mintable: ").append(toIndentedString(mintable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
