/*
 * GoPlus Security API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.gopluslabs.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gopluslabs.client.model.ResponseWrapperGetScanResultResultTokenAttentionRiskDetail;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * ResponseWrapperGetScanResultResultTokenAttention
 */



public class ResponseWrapperGetScanResultResultTokenAttention {
  @SerializedName("risk_num")
  private Integer riskNum = null;

  @SerializedName("risk_detail")
  private List<ResponseWrapperGetScanResultResultTokenAttentionRiskDetail> riskDetail = null;

  public ResponseWrapperGetScanResultResultTokenAttention riskNum(Integer riskNum) {
    this.riskNum = riskNum;
    return this;
  }

   /**
   * Get riskNum
   * @return riskNum
  **/
  @Schema(description = "")
  public Integer getRiskNum() {
    return riskNum;
  }

  public void setRiskNum(Integer riskNum) {
    this.riskNum = riskNum;
  }

  public ResponseWrapperGetScanResultResultTokenAttention riskDetail(List<ResponseWrapperGetScanResultResultTokenAttentionRiskDetail> riskDetail) {
    this.riskDetail = riskDetail;
    return this;
  }

  public ResponseWrapperGetScanResultResultTokenAttention addRiskDetailItem(ResponseWrapperGetScanResultResultTokenAttentionRiskDetail riskDetailItem) {
    if (this.riskDetail == null) {
      this.riskDetail = new ArrayList<ResponseWrapperGetScanResultResultTokenAttentionRiskDetail>();
    }
    this.riskDetail.add(riskDetailItem);
    return this;
  }

   /**
   * Get riskDetail
   * @return riskDetail
  **/
  @Schema(description = "")
  public List<ResponseWrapperGetScanResultResultTokenAttentionRiskDetail> getRiskDetail() {
    return riskDetail;
  }

  public void setRiskDetail(List<ResponseWrapperGetScanResultResultTokenAttentionRiskDetail> riskDetail) {
    this.riskDetail = riskDetail;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseWrapperGetScanResultResultTokenAttention responseWrapperGetScanResultResultTokenAttention = (ResponseWrapperGetScanResultResultTokenAttention) o;
    return Objects.equals(this.riskNum, responseWrapperGetScanResultResultTokenAttention.riskNum) &&
        Objects.equals(this.riskDetail, responseWrapperGetScanResultResultTokenAttention.riskDetail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(riskNum, riskDetail);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseWrapperGetScanResultResultTokenAttention {\n");
    
    sb.append("    riskNum: ").append(toIndentedString(riskNum)).append("\n");
    sb.append("    riskDetail: ").append(toIndentedString(riskDetail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
