/*
 * GoPlus Security API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.gopluslabs.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * It describes the whitelist permission of the B20 token.
 */
@Schema(description = "It describes the whitelist permission of the B20 token.")


public class ResponseWrapperTokenSecurityB20TokenB20InfoWhitelist {
  @SerializedName("admin")
  private List<String> admin = null;

  @SerializedName("status")
  private String status = null;

  public ResponseWrapperTokenSecurityB20TokenB20InfoWhitelist admin(List<String> admin) {
    this.admin = admin;
    return this;
  }

  public ResponseWrapperTokenSecurityB20TokenB20InfoWhitelist addAdminItem(String adminItem) {
    if (this.admin == null) {
      this.admin = new ArrayList<String>();
    }
    this.admin.add(adminItem);
    return this;
  }

   /**
   * It describes the admin addresses who have the whitelist permission.  Example: [\&quot;0x71ae788403067678fb509f1a018ce5cb50bca444\&quot;]
   * @return admin
  **/
  @Schema(description = "It describes the admin addresses who have the whitelist permission.  Example: [\"0x71ae788403067678fb509f1a018ce5cb50bca444\"]")
  public List<String> getAdmin() {
    return admin;
  }

  public void setAdmin(List<String> admin) {
    this.admin = admin;
  }

  public ResponseWrapperTokenSecurityB20TokenB20InfoWhitelist status(String status) {
    this.status = status;
    return this;
  }

   /**
   * It describes whether the whitelist permission is enabled.  \&quot;1\&quot; means enabled;  \&quot;0\&quot; means disabled;
   * @return status
  **/
  @Schema(description = "It describes whether the whitelist permission is enabled.  \"1\" means enabled;  \"0\" means disabled;")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseWrapperTokenSecurityB20TokenB20InfoWhitelist responseWrapperTokenSecurityB20TokenB20InfoWhitelist = (ResponseWrapperTokenSecurityB20TokenB20InfoWhitelist) o;
    return Objects.equals(this.admin, responseWrapperTokenSecurityB20TokenB20InfoWhitelist.admin) &&
        Objects.equals(this.status, responseWrapperTokenSecurityB20TokenB20InfoWhitelist.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(admin, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseWrapperTokenSecurityB20TokenB20InfoWhitelist {\n");
    
    sb.append("    admin: ").append(toIndentedString(admin)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
