/*
 * GoPlus Security API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.gopluslabs.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gopluslabs.client.model.ResponseWrapperTokenSecurityB20TokenB20Info;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * It describes the B20 token information. (Notice: Only returned when the token is a B20 token and new account.)
 */
@Schema(description = "It describes the B20 token information. (Notice: Only returned when the token is a B20 token and new account.)")


public class ResponseWrapperTokenSecurityB20Token {
  @SerializedName("is_b20_token")
  private String isB20Token = null;

  @SerializedName("b20_info")
  private ResponseWrapperTokenSecurityB20TokenB20Info b20Info = null;

  public ResponseWrapperTokenSecurityB20Token isB20Token(String isB20Token) {
    this.isB20Token = isB20Token;
    return this;
  }

   /**
   * It describes whether the token is a B20 token.  \&quot;1\&quot; means true;  \&quot;0\&quot; means false;
   * @return isB20Token
  **/
  @Schema(description = "It describes whether the token is a B20 token.  \"1\" means true;  \"0\" means false;")
  public String getIsB20Token() {
    return isB20Token;
  }

  public void setIsB20Token(String isB20Token) {
    this.isB20Token = isB20Token;
  }

  public ResponseWrapperTokenSecurityB20Token b20Info(ResponseWrapperTokenSecurityB20TokenB20Info b20Info) {
    this.b20Info = b20Info;
    return this;
  }

   /**
   * Get b20Info
   * @return b20Info
  **/
  @Schema(description = "")
  public ResponseWrapperTokenSecurityB20TokenB20Info getB20Info() {
    return b20Info;
  }

  public void setB20Info(ResponseWrapperTokenSecurityB20TokenB20Info b20Info) {
    this.b20Info = b20Info;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseWrapperTokenSecurityB20Token responseWrapperTokenSecurityB20Token = (ResponseWrapperTokenSecurityB20Token) o;
    return Objects.equals(this.isB20Token, responseWrapperTokenSecurityB20Token.isB20Token) &&
        Objects.equals(this.b20Info, responseWrapperTokenSecurityB20Token.b20Info);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isB20Token, b20Info);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseWrapperTokenSecurityB20Token {\n");
    
    sb.append("    isB20Token: ").append(toIndentedString(isB20Token)).append("\n");
    sb.append("    b20Info: ").append(toIndentedString(b20Info)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
