/*
 * GoPlus Security API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.gopluslabs.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gopluslabs.client.model.ResponseWrapperGetScanResultResultAddressPoisonedRiskDetail;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * ResponseWrapperGetScanResultResultAddressPoisoned
 */



public class ResponseWrapperGetScanResultResultAddressPoisoned {
  @SerializedName("risk_num")
  private Integer riskNum = null;

  @SerializedName("risk_detail")
  private List<ResponseWrapperGetScanResultResultAddressPoisonedRiskDetail> riskDetail = null;

  public ResponseWrapperGetScanResultResultAddressPoisoned riskNum(Integer riskNum) {
    this.riskNum = riskNum;
    return this;
  }

   /**
   * Get riskNum
   * @return riskNum
  **/
  @Schema(description = "")
  public Integer getRiskNum() {
    return riskNum;
  }

  public void setRiskNum(Integer riskNum) {
    this.riskNum = riskNum;
  }

  public ResponseWrapperGetScanResultResultAddressPoisoned riskDetail(List<ResponseWrapperGetScanResultResultAddressPoisonedRiskDetail> riskDetail) {
    this.riskDetail = riskDetail;
    return this;
  }

  public ResponseWrapperGetScanResultResultAddressPoisoned addRiskDetailItem(ResponseWrapperGetScanResultResultAddressPoisonedRiskDetail riskDetailItem) {
    if (this.riskDetail == null) {
      this.riskDetail = new ArrayList<ResponseWrapperGetScanResultResultAddressPoisonedRiskDetail>();
    }
    this.riskDetail.add(riskDetailItem);
    return this;
  }

   /**
   * Get riskDetail
   * @return riskDetail
  **/
  @Schema(description = "")
  public List<ResponseWrapperGetScanResultResultAddressPoisonedRiskDetail> getRiskDetail() {
    return riskDetail;
  }

  public void setRiskDetail(List<ResponseWrapperGetScanResultResultAddressPoisonedRiskDetail> riskDetail) {
    this.riskDetail = riskDetail;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseWrapperGetScanResultResultAddressPoisoned responseWrapperGetScanResultResultAddressPoisoned = (ResponseWrapperGetScanResultResultAddressPoisoned) o;
    return Objects.equals(this.riskNum, responseWrapperGetScanResultResultAddressPoisoned.riskNum) &&
        Objects.equals(this.riskDetail, responseWrapperGetScanResultResultAddressPoisoned.riskDetail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(riskNum, riskDetail);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseWrapperGetScanResultResultAddressPoisoned {\n");
    
    sb.append("    riskNum: ").append(toIndentedString(riskNum)).append("\n");
    sb.append("    riskDetail: ").append(toIndentedString(riskDetail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
