/*
 * GoPlus Security API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.gopluslabs.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gopluslabs.client.model.ResponseWrapperSolanaTokenSecurityTransferFeeCurrentFeeRate;
import io.gopluslabs.client.model.ResponseWrapperSolanaTokenSecurityTransferFeeScheduledFeeRate;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Configuration information for transfer fees.(Notice: \&quot;Scheduled Fee\&quot; would take effect and turn into \&quot;Current Fee\&quot; when the epoch is reached.)
 */
@Schema(description = "Configuration information for transfer fees.(Notice: \"Scheduled Fee\" would take effect and turn into \"Current Fee\" when the epoch is reached.)")


public class ResponseWrapperSolanaTokenSecurityTransferFee {
  @SerializedName("scheduled_fee_rate")
  private List<ResponseWrapperSolanaTokenSecurityTransferFeeScheduledFeeRate> scheduledFeeRate = null;

  @SerializedName("current_fee_rate")
  private ResponseWrapperSolanaTokenSecurityTransferFeeCurrentFeeRate currentFeeRate = null;

  public ResponseWrapperSolanaTokenSecurityTransferFee scheduledFeeRate(List<ResponseWrapperSolanaTokenSecurityTransferFeeScheduledFeeRate> scheduledFeeRate) {
    this.scheduledFeeRate = scheduledFeeRate;
    return this;
  }

  public ResponseWrapperSolanaTokenSecurityTransferFee addScheduledFeeRateItem(ResponseWrapperSolanaTokenSecurityTransferFeeScheduledFeeRate scheduledFeeRateItem) {
    if (this.scheduledFeeRate == null) {
      this.scheduledFeeRate = new ArrayList<ResponseWrapperSolanaTokenSecurityTransferFeeScheduledFeeRate>();
    }
    this.scheduledFeeRate.add(scheduledFeeRateItem);
    return this;
  }

   /**
   * Scheduled changes to transfer fee rates.
   * @return scheduledFeeRate
  **/
  @Schema(description = "Scheduled changes to transfer fee rates.")
  public List<ResponseWrapperSolanaTokenSecurityTransferFeeScheduledFeeRate> getScheduledFeeRate() {
    return scheduledFeeRate;
  }

  public void setScheduledFeeRate(List<ResponseWrapperSolanaTokenSecurityTransferFeeScheduledFeeRate> scheduledFeeRate) {
    this.scheduledFeeRate = scheduledFeeRate;
  }

  public ResponseWrapperSolanaTokenSecurityTransferFee currentFeeRate(ResponseWrapperSolanaTokenSecurityTransferFeeCurrentFeeRate currentFeeRate) {
    this.currentFeeRate = currentFeeRate;
    return this;
  }

   /**
   * Get currentFeeRate
   * @return currentFeeRate
  **/
  @Schema(description = "")
  public ResponseWrapperSolanaTokenSecurityTransferFeeCurrentFeeRate getCurrentFeeRate() {
    return currentFeeRate;
  }

  public void setCurrentFeeRate(ResponseWrapperSolanaTokenSecurityTransferFeeCurrentFeeRate currentFeeRate) {
    this.currentFeeRate = currentFeeRate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseWrapperSolanaTokenSecurityTransferFee responseWrapperSolanaTokenSecurityTransferFee = (ResponseWrapperSolanaTokenSecurityTransferFee) o;
    return Objects.equals(this.scheduledFeeRate, responseWrapperSolanaTokenSecurityTransferFee.scheduledFeeRate) &&
        Objects.equals(this.currentFeeRate, responseWrapperSolanaTokenSecurityTransferFee.currentFeeRate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(scheduledFeeRate, currentFeeRate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseWrapperSolanaTokenSecurityTransferFee {\n");
    
    sb.append("    scheduledFeeRate: ").append(toIndentedString(scheduledFeeRate)).append("\n");
    sb.append("    currentFeeRate: ").append(toIndentedString(currentFeeRate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
