/*
 * GoPlus Security API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.gopluslabs.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gopluslabs.client.model.ResponseWrapperSolanaTokenSecurityDay;
import io.gopluslabs.client.model.ResponseWrapperSolanaTokenSecurityMonth;
import io.gopluslabs.client.model.ResponseWrapperSolanaTokenSecurityWeek;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * ResponseWrapperSolanaTokenSecurityDex
 */



public class ResponseWrapperSolanaTokenSecurityDex {
  @SerializedName("week")
  private ResponseWrapperSolanaTokenSecurityWeek week = null;

  @SerializedName("month")
  private ResponseWrapperSolanaTokenSecurityMonth month = null;

  @SerializedName("price")
  private String price = null;

  @SerializedName("open_time")
  private String openTime = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("tvl")
  private String tvl = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("dex_name")
  private String dexName = null;

  @SerializedName("day")
  private ResponseWrapperSolanaTokenSecurityDay day = null;

  @SerializedName("burn_percent")
  private BigDecimal burnPercent = null;

  @SerializedName("lp_amount")
  private String lpAmount = null;

  @SerializedName("fee_rate")
  private String feeRate = null;

  public ResponseWrapperSolanaTokenSecurityDex week(ResponseWrapperSolanaTokenSecurityWeek week) {
    this.week = week;
    return this;
  }

   /**
   * Get week
   * @return week
  **/
  @Schema(description = "")
  public ResponseWrapperSolanaTokenSecurityWeek getWeek() {
    return week;
  }

  public void setWeek(ResponseWrapperSolanaTokenSecurityWeek week) {
    this.week = week;
  }

  public ResponseWrapperSolanaTokenSecurityDex month(ResponseWrapperSolanaTokenSecurityMonth month) {
    this.month = month;
    return this;
  }

   /**
   * Get month
   * @return month
  **/
  @Schema(description = "")
  public ResponseWrapperSolanaTokenSecurityMonth getMonth() {
    return month;
  }

  public void setMonth(ResponseWrapperSolanaTokenSecurityMonth month) {
    this.month = month;
  }

  public ResponseWrapperSolanaTokenSecurityDex price(String price) {
    this.price = price;
    return this;
  }

   /**
   * Current price (Unitless, count by two tokens in the pool).
   * @return price
  **/
  @Schema(description = "Current price (Unitless, count by two tokens in the pool).")
  public String getPrice() {
    return price;
  }

  public void setPrice(String price) {
    this.price = price;
  }

  public ResponseWrapperSolanaTokenSecurityDex openTime(String openTime) {
    this.openTime = openTime;
    return this;
  }

   /**
   * The epoch when trading is opened.
   * @return openTime
  **/
  @Schema(description = "The epoch when trading is opened.")
  public String getOpenTime() {
    return openTime;
  }

  public void setOpenTime(String openTime) {
    this.openTime = openTime;
  }

  public ResponseWrapperSolanaTokenSecurityDex id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Address of the liquidity pool.
   * @return id
  **/
  @Schema(description = "Address of the liquidity pool.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ResponseWrapperSolanaTokenSecurityDex tvl(String tvl) {
    this.tvl = tvl;
    return this;
  }

   /**
   * Total value locked (TVL) in the liquidity pool.
   * @return tvl
  **/
  @Schema(description = "Total value locked (TVL) in the liquidity pool.")
  public String getTvl() {
    return tvl;
  }

  public void setTvl(String tvl) {
    this.tvl = tvl;
  }

  public ResponseWrapperSolanaTokenSecurityDex type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Type of the DEX, could be \&quot;standard\&quot; or \&quot;concentrated\&quot;.
   * @return type
  **/
  @Schema(description = "Type of the DEX, could be \"standard\" or \"concentrated\".")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public ResponseWrapperSolanaTokenSecurityDex dexName(String dexName) {
    this.dexName = dexName;
    return this;
  }

   /**
   * Name of the DEX.
   * @return dexName
  **/
  @Schema(description = "Name of the DEX.")
  public String getDexName() {
    return dexName;
  }

  public void setDexName(String dexName) {
    this.dexName = dexName;
  }

  public ResponseWrapperSolanaTokenSecurityDex day(ResponseWrapperSolanaTokenSecurityDay day) {
    this.day = day;
    return this;
  }

   /**
   * Get day
   * @return day
  **/
  @Schema(description = "")
  public ResponseWrapperSolanaTokenSecurityDay getDay() {
    return day;
  }

  public void setDay(ResponseWrapperSolanaTokenSecurityDay day) {
    this.day = day;
  }

  public ResponseWrapperSolanaTokenSecurityDex burnPercent(BigDecimal burnPercent) {
    this.burnPercent = burnPercent;
    return this;
  }

   /**
   * Percentage of burned LP
   * @return burnPercent
  **/
  @Schema(description = "Percentage of burned LP")
  public BigDecimal getBurnPercent() {
    return burnPercent;
  }

  public void setBurnPercent(BigDecimal burnPercent) {
    this.burnPercent = burnPercent;
  }

  public ResponseWrapperSolanaTokenSecurityDex lpAmount(String lpAmount) {
    this.lpAmount = lpAmount;
    return this;
  }

   /**
   * Total amount of liquidity provider tokens, only shown when type is \&quot;standard\&quot;
   * @return lpAmount
  **/
  @Schema(description = "Total amount of liquidity provider tokens, only shown when type is \"standard\"")
  public String getLpAmount() {
    return lpAmount;
  }

  public void setLpAmount(String lpAmount) {
    this.lpAmount = lpAmount;
  }

  public ResponseWrapperSolanaTokenSecurityDex feeRate(String feeRate) {
    this.feeRate = feeRate;
    return this;
  }

   /**
   * Transaction fee rate.
   * @return feeRate
  **/
  @Schema(description = "Transaction fee rate.")
  public String getFeeRate() {
    return feeRate;
  }

  public void setFeeRate(String feeRate) {
    this.feeRate = feeRate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseWrapperSolanaTokenSecurityDex responseWrapperSolanaTokenSecurityDex = (ResponseWrapperSolanaTokenSecurityDex) o;
    return Objects.equals(this.week, responseWrapperSolanaTokenSecurityDex.week) &&
        Objects.equals(this.month, responseWrapperSolanaTokenSecurityDex.month) &&
        Objects.equals(this.price, responseWrapperSolanaTokenSecurityDex.price) &&
        Objects.equals(this.openTime, responseWrapperSolanaTokenSecurityDex.openTime) &&
        Objects.equals(this.id, responseWrapperSolanaTokenSecurityDex.id) &&
        Objects.equals(this.tvl, responseWrapperSolanaTokenSecurityDex.tvl) &&
        Objects.equals(this.type, responseWrapperSolanaTokenSecurityDex.type) &&
        Objects.equals(this.dexName, responseWrapperSolanaTokenSecurityDex.dexName) &&
        Objects.equals(this.day, responseWrapperSolanaTokenSecurityDex.day) &&
        Objects.equals(this.burnPercent, responseWrapperSolanaTokenSecurityDex.burnPercent) &&
        Objects.equals(this.lpAmount, responseWrapperSolanaTokenSecurityDex.lpAmount) &&
        Objects.equals(this.feeRate, responseWrapperSolanaTokenSecurityDex.feeRate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(week, month, price, openTime, id, tvl, type, dexName, day, burnPercent, lpAmount, feeRate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseWrapperSolanaTokenSecurityDex {\n");
    
    sb.append("    week: ").append(toIndentedString(week)).append("\n");
    sb.append("    month: ").append(toIndentedString(month)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    openTime: ").append(toIndentedString(openTime)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    tvl: ").append(toIndentedString(tvl)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    dexName: ").append(toIndentedString(dexName)).append("\n");
    sb.append("    day: ").append(toIndentedString(day)).append("\n");
    sb.append("    burnPercent: ").append(toIndentedString(burnPercent)).append("\n");
    sb.append("    lpAmount: ").append(toIndentedString(lpAmount)).append("\n");
    sb.append("    feeRate: ").append(toIndentedString(feeRate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
