/*
 * GoPlus Security API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.gopluslabs.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ResponseWrapperSolanaTokenSecurityTransferFeeScheduledFeeRate
 */



public class ResponseWrapperSolanaTokenSecurityTransferFeeScheduledFeeRate {
  @SerializedName("maximum_fee")
  private String maximumFee = null;

  @SerializedName("epoch")
  private String epoch = null;

  @SerializedName("fee_rate")
  private String feeRate = null;

  public ResponseWrapperSolanaTokenSecurityTransferFeeScheduledFeeRate maximumFee(String maximumFee) {
    this.maximumFee = maximumFee;
    return this;
  }

   /**
   * Maximum fee amount for a single transaction.
   * @return maximumFee
  **/
  @Schema(description = "Maximum fee amount for a single transaction.")
  public String getMaximumFee() {
    return maximumFee;
  }

  public void setMaximumFee(String maximumFee) {
    this.maximumFee = maximumFee;
  }

  public ResponseWrapperSolanaTokenSecurityTransferFeeScheduledFeeRate epoch(String epoch) {
    this.epoch = epoch;
    return this;
  }

   /**
   * The epoch at which the fee rate will take effect.
   * @return epoch
  **/
  @Schema(description = "The epoch at which the fee rate will take effect.")
  public String getEpoch() {
    return epoch;
  }

  public void setEpoch(String epoch) {
    this.epoch = epoch;
  }

  public ResponseWrapperSolanaTokenSecurityTransferFeeScheduledFeeRate feeRate(String feeRate) {
    this.feeRate = feeRate;
    return this;
  }

   /**
   * Fee rate (expressed as a ratio, e.g., 0.02 means 2%)
   * @return feeRate
  **/
  @Schema(description = "Fee rate (expressed as a ratio, e.g., 0.02 means 2%)")
  public String getFeeRate() {
    return feeRate;
  }

  public void setFeeRate(String feeRate) {
    this.feeRate = feeRate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseWrapperSolanaTokenSecurityTransferFeeScheduledFeeRate responseWrapperSolanaTokenSecurityTransferFeeScheduledFeeRate = (ResponseWrapperSolanaTokenSecurityTransferFeeScheduledFeeRate) o;
    return Objects.equals(this.maximumFee, responseWrapperSolanaTokenSecurityTransferFeeScheduledFeeRate.maximumFee) &&
        Objects.equals(this.epoch, responseWrapperSolanaTokenSecurityTransferFeeScheduledFeeRate.epoch) &&
        Objects.equals(this.feeRate, responseWrapperSolanaTokenSecurityTransferFeeScheduledFeeRate.feeRate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maximumFee, epoch, feeRate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseWrapperSolanaTokenSecurityTransferFeeScheduledFeeRate {\n");
    
    sb.append("    maximumFee: ").append(toIndentedString(maximumFee)).append("\n");
    sb.append("    epoch: ").append(toIndentedString(epoch)).append("\n");
    sb.append("    feeRate: ").append(toIndentedString(feeRate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
