/*
 * GoPlus Security API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.gopluslabs.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ResponseWrapperSolanaTokenSecurityCreator
 */



public class ResponseWrapperSolanaTokenSecurityCreator {
  @SerializedName("address")
  private String address = null;

  @SerializedName("malicious_address")
  private Integer maliciousAddress = null;

  public ResponseWrapperSolanaTokenSecurityCreator address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Address of the creator.
   * @return address
  **/
  @Schema(description = "Address of the creator.")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public ResponseWrapperSolanaTokenSecurityCreator maliciousAddress(Integer maliciousAddress) {
    this.maliciousAddress = maliciousAddress;
    return this;
  }

   /**
   * Indicates whether the address is malicious, \&quot;1\&quot; means yes.
   * @return maliciousAddress
  **/
  @Schema(description = "Indicates whether the address is malicious, \"1\" means yes.")
  public Integer getMaliciousAddress() {
    return maliciousAddress;
  }

  public void setMaliciousAddress(Integer maliciousAddress) {
    this.maliciousAddress = maliciousAddress;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseWrapperSolanaTokenSecurityCreator responseWrapperSolanaTokenSecurityCreator = (ResponseWrapperSolanaTokenSecurityCreator) o;
    return Objects.equals(this.address, responseWrapperSolanaTokenSecurityCreator.address) &&
        Objects.equals(this.maliciousAddress, responseWrapperSolanaTokenSecurityCreator.maliciousAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, maliciousAddress);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseWrapperSolanaTokenSecurityCreator {\n");
    
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    maliciousAddress: ").append(toIndentedString(maliciousAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
