/*
 * GoPlus Security API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.gopluslabs.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ResponseWrapperGetScanResultResultApprovalRiskErc20Risk
 */



public class ResponseWrapperGetScanResultResultApprovalRiskErc20Risk {
  @SerializedName("transaction_time")
  private String transactionTime = null;

  @SerializedName("token_address")
  private String tokenAddress = null;

  @SerializedName("token_symbol")
  private String tokenSymbol = null;

  @SerializedName("approved_amount")
  private String approvedAmount = null;

  @SerializedName("transaction_hash")
  private String transactionHash = null;

  @SerializedName("approved_address")
  private String approvedAddress = null;

  public ResponseWrapperGetScanResultResultApprovalRiskErc20Risk transactionTime(String transactionTime) {
    this.transactionTime = transactionTime;
    return this;
  }

   /**
   * Get transactionTime
   * @return transactionTime
  **/
  @Schema(description = "")
  public String getTransactionTime() {
    return transactionTime;
  }

  public void setTransactionTime(String transactionTime) {
    this.transactionTime = transactionTime;
  }

  public ResponseWrapperGetScanResultResultApprovalRiskErc20Risk tokenAddress(String tokenAddress) {
    this.tokenAddress = tokenAddress;
    return this;
  }

   /**
   * Get tokenAddress
   * @return tokenAddress
  **/
  @Schema(description = "")
  public String getTokenAddress() {
    return tokenAddress;
  }

  public void setTokenAddress(String tokenAddress) {
    this.tokenAddress = tokenAddress;
  }

  public ResponseWrapperGetScanResultResultApprovalRiskErc20Risk tokenSymbol(String tokenSymbol) {
    this.tokenSymbol = tokenSymbol;
    return this;
  }

   /**
   * Get tokenSymbol
   * @return tokenSymbol
  **/
  @Schema(description = "")
  public String getTokenSymbol() {
    return tokenSymbol;
  }

  public void setTokenSymbol(String tokenSymbol) {
    this.tokenSymbol = tokenSymbol;
  }

  public ResponseWrapperGetScanResultResultApprovalRiskErc20Risk approvedAmount(String approvedAmount) {
    this.approvedAmount = approvedAmount;
    return this;
  }

   /**
   * Get approvedAmount
   * @return approvedAmount
  **/
  @Schema(description = "")
  public String getApprovedAmount() {
    return approvedAmount;
  }

  public void setApprovedAmount(String approvedAmount) {
    this.approvedAmount = approvedAmount;
  }

  public ResponseWrapperGetScanResultResultApprovalRiskErc20Risk transactionHash(String transactionHash) {
    this.transactionHash = transactionHash;
    return this;
  }

   /**
   * Get transactionHash
   * @return transactionHash
  **/
  @Schema(description = "")
  public String getTransactionHash() {
    return transactionHash;
  }

  public void setTransactionHash(String transactionHash) {
    this.transactionHash = transactionHash;
  }

  public ResponseWrapperGetScanResultResultApprovalRiskErc20Risk approvedAddress(String approvedAddress) {
    this.approvedAddress = approvedAddress;
    return this;
  }

   /**
   * Get approvedAddress
   * @return approvedAddress
  **/
  @Schema(description = "")
  public String getApprovedAddress() {
    return approvedAddress;
  }

  public void setApprovedAddress(String approvedAddress) {
    this.approvedAddress = approvedAddress;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseWrapperGetScanResultResultApprovalRiskErc20Risk responseWrapperGetScanResultResultApprovalRiskErc20Risk = (ResponseWrapperGetScanResultResultApprovalRiskErc20Risk) o;
    return Objects.equals(this.transactionTime, responseWrapperGetScanResultResultApprovalRiskErc20Risk.transactionTime) &&
        Objects.equals(this.tokenAddress, responseWrapperGetScanResultResultApprovalRiskErc20Risk.tokenAddress) &&
        Objects.equals(this.tokenSymbol, responseWrapperGetScanResultResultApprovalRiskErc20Risk.tokenSymbol) &&
        Objects.equals(this.approvedAmount, responseWrapperGetScanResultResultApprovalRiskErc20Risk.approvedAmount) &&
        Objects.equals(this.transactionHash, responseWrapperGetScanResultResultApprovalRiskErc20Risk.transactionHash) &&
        Objects.equals(this.approvedAddress, responseWrapperGetScanResultResultApprovalRiskErc20Risk.approvedAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionTime, tokenAddress, tokenSymbol, approvedAmount, transactionHash, approvedAddress);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseWrapperGetScanResultResultApprovalRiskErc20Risk {\n");
    
    sb.append("    transactionTime: ").append(toIndentedString(transactionTime)).append("\n");
    sb.append("    tokenAddress: ").append(toIndentedString(tokenAddress)).append("\n");
    sb.append("    tokenSymbol: ").append(toIndentedString(tokenSymbol)).append("\n");
    sb.append("    approvedAmount: ").append(toIndentedString(approvedAmount)).append("\n");
    sb.append("    transactionHash: ").append(toIndentedString(transactionHash)).append("\n");
    sb.append("    approvedAddress: ").append(toIndentedString(approvedAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
