/*
 * GoPlus Security API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.gopluslabs.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ResponseWrapperGetScanResultResultAddressPoisonedRiskDetail
 */



public class ResponseWrapperGetScanResultResultAddressPoisonedRiskDetail {
  @SerializedName("transaction_time")
  private String transactionTime = null;

  @SerializedName("transaction_hash")
  private String transactionHash = null;

  public ResponseWrapperGetScanResultResultAddressPoisonedRiskDetail transactionTime(String transactionTime) {
    this.transactionTime = transactionTime;
    return this;
  }

   /**
   * Get transactionTime
   * @return transactionTime
  **/
  @Schema(description = "")
  public String getTransactionTime() {
    return transactionTime;
  }

  public void setTransactionTime(String transactionTime) {
    this.transactionTime = transactionTime;
  }

  public ResponseWrapperGetScanResultResultAddressPoisonedRiskDetail transactionHash(String transactionHash) {
    this.transactionHash = transactionHash;
    return this;
  }

   /**
   * Get transactionHash
   * @return transactionHash
  **/
  @Schema(description = "")
  public String getTransactionHash() {
    return transactionHash;
  }

  public void setTransactionHash(String transactionHash) {
    this.transactionHash = transactionHash;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseWrapperGetScanResultResultAddressPoisonedRiskDetail responseWrapperGetScanResultResultAddressPoisonedRiskDetail = (ResponseWrapperGetScanResultResultAddressPoisonedRiskDetail) o;
    return Objects.equals(this.transactionTime, responseWrapperGetScanResultResultAddressPoisonedRiskDetail.transactionTime) &&
        Objects.equals(this.transactionHash, responseWrapperGetScanResultResultAddressPoisonedRiskDetail.transactionHash);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionTime, transactionHash);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseWrapperGetScanResultResultAddressPoisonedRiskDetail {\n");
    
    sb.append("    transactionTime: ").append(toIndentedString(transactionTime)).append("\n");
    sb.append("    transactionHash: ").append(toIndentedString(transactionHash)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
