/*
 * GoPlus Security API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.gopluslabs.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SolanaTxSolChange
 */



public class SolanaTxSolChange {
  @SerializedName("address")
  private String address = null;

  @SerializedName("post_lamports")
  private String postLamports = null;

  @SerializedName("lamport_changes")
  private String lamportChanges = null;

  @SerializedName("risky_address")
  private Integer riskyAddress = null;

  @SerializedName("from_address")
  private Integer fromAddress = null;

  @SerializedName("pre_lamports")
  private String preLamports = null;

  public SolanaTxSolChange address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @Schema(description = "")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public SolanaTxSolChange postLamports(String postLamports) {
    this.postLamports = postLamports;
    return this;
  }

   /**
   * Get postLamports
   * @return postLamports
  **/
  @Schema(description = "")
  public String getPostLamports() {
    return postLamports;
  }

  public void setPostLamports(String postLamports) {
    this.postLamports = postLamports;
  }

  public SolanaTxSolChange lamportChanges(String lamportChanges) {
    this.lamportChanges = lamportChanges;
    return this;
  }

   /**
   * Get lamportChanges
   * @return lamportChanges
  **/
  @Schema(description = "")
  public String getLamportChanges() {
    return lamportChanges;
  }

  public void setLamportChanges(String lamportChanges) {
    this.lamportChanges = lamportChanges;
  }

  public SolanaTxSolChange riskyAddress(Integer riskyAddress) {
    this.riskyAddress = riskyAddress;
    return this;
  }

   /**
   * Get riskyAddress
   * @return riskyAddress
  **/
  @Schema(description = "")
  public Integer getRiskyAddress() {
    return riskyAddress;
  }

  public void setRiskyAddress(Integer riskyAddress) {
    this.riskyAddress = riskyAddress;
  }

  public SolanaTxSolChange fromAddress(Integer fromAddress) {
    this.fromAddress = fromAddress;
    return this;
  }

   /**
   * Get fromAddress
   * @return fromAddress
  **/
  @Schema(description = "")
  public Integer getFromAddress() {
    return fromAddress;
  }

  public void setFromAddress(Integer fromAddress) {
    this.fromAddress = fromAddress;
  }

  public SolanaTxSolChange preLamports(String preLamports) {
    this.preLamports = preLamports;
    return this;
  }

   /**
   * Get preLamports
   * @return preLamports
  **/
  @Schema(description = "")
  public String getPreLamports() {
    return preLamports;
  }

  public void setPreLamports(String preLamports) {
    this.preLamports = preLamports;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SolanaTxSolChange solanaTxSolChange = (SolanaTxSolChange) o;
    return Objects.equals(this.address, solanaTxSolChange.address) &&
        Objects.equals(this.postLamports, solanaTxSolChange.postLamports) &&
        Objects.equals(this.lamportChanges, solanaTxSolChange.lamportChanges) &&
        Objects.equals(this.riskyAddress, solanaTxSolChange.riskyAddress) &&
        Objects.equals(this.fromAddress, solanaTxSolChange.fromAddress) &&
        Objects.equals(this.preLamports, solanaTxSolChange.preLamports);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, postLamports, lamportChanges, riskyAddress, fromAddress, preLamports);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SolanaTxSolChange {\n");
    
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    postLamports: ").append(toIndentedString(postLamports)).append("\n");
    sb.append("    lamportChanges: ").append(toIndentedString(lamportChanges)).append("\n");
    sb.append("    riskyAddress: ").append(toIndentedString(riskyAddress)).append("\n");
    sb.append("    fromAddress: ").append(toIndentedString(fromAddress)).append("\n");
    sb.append("    preLamports: ").append(toIndentedString(preLamports)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
