/*
 * GoPlus Security API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.gopluslabs.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SolanaOwnershipChange
 */



public class SolanaOwnershipChange {
  @SerializedName("mint")
  private String mint = null;

  @SerializedName("symbol")
  private String symbol = null;

  @SerializedName("post_owner")
  private String postOwner = null;

  @SerializedName("decimals")
  private Integer decimals = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("pre_owner")
  private String preOwner = null;

  @SerializedName("owner_changed")
  private String ownerChanged = null;

  @SerializedName("risky_post_owner")
  private Integer riskyPostOwner = null;

  public SolanaOwnershipChange mint(String mint) {
    this.mint = mint;
    return this;
  }

   /**
   * Get mint
   * @return mint
  **/
  @Schema(description = "")
  public String getMint() {
    return mint;
  }

  public void setMint(String mint) {
    this.mint = mint;
  }

  public SolanaOwnershipChange symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Get symbol
   * @return symbol
  **/
  @Schema(description = "")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public SolanaOwnershipChange postOwner(String postOwner) {
    this.postOwner = postOwner;
    return this;
  }

   /**
   * Get postOwner
   * @return postOwner
  **/
  @Schema(description = "")
  public String getPostOwner() {
    return postOwner;
  }

  public void setPostOwner(String postOwner) {
    this.postOwner = postOwner;
  }

  public SolanaOwnershipChange decimals(Integer decimals) {
    this.decimals = decimals;
    return this;
  }

   /**
   * Get decimals
   * @return decimals
  **/
  @Schema(description = "")
  public Integer getDecimals() {
    return decimals;
  }

  public void setDecimals(Integer decimals) {
    this.decimals = decimals;
  }

  public SolanaOwnershipChange name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SolanaOwnershipChange preOwner(String preOwner) {
    this.preOwner = preOwner;
    return this;
  }

   /**
   * Get preOwner
   * @return preOwner
  **/
  @Schema(description = "")
  public String getPreOwner() {
    return preOwner;
  }

  public void setPreOwner(String preOwner) {
    this.preOwner = preOwner;
  }

  public SolanaOwnershipChange ownerChanged(String ownerChanged) {
    this.ownerChanged = ownerChanged;
    return this;
  }

   /**
   * Get ownerChanged
   * @return ownerChanged
  **/
  @Schema(description = "")
  public String getOwnerChanged() {
    return ownerChanged;
  }

  public void setOwnerChanged(String ownerChanged) {
    this.ownerChanged = ownerChanged;
  }

  public SolanaOwnershipChange riskyPostOwner(Integer riskyPostOwner) {
    this.riskyPostOwner = riskyPostOwner;
    return this;
  }

   /**
   * Get riskyPostOwner
   * @return riskyPostOwner
  **/
  @Schema(description = "")
  public Integer getRiskyPostOwner() {
    return riskyPostOwner;
  }

  public void setRiskyPostOwner(Integer riskyPostOwner) {
    this.riskyPostOwner = riskyPostOwner;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SolanaOwnershipChange solanaOwnershipChange = (SolanaOwnershipChange) o;
    return Objects.equals(this.mint, solanaOwnershipChange.mint) &&
        Objects.equals(this.symbol, solanaOwnershipChange.symbol) &&
        Objects.equals(this.postOwner, solanaOwnershipChange.postOwner) &&
        Objects.equals(this.decimals, solanaOwnershipChange.decimals) &&
        Objects.equals(this.name, solanaOwnershipChange.name) &&
        Objects.equals(this.preOwner, solanaOwnershipChange.preOwner) &&
        Objects.equals(this.ownerChanged, solanaOwnershipChange.ownerChanged) &&
        Objects.equals(this.riskyPostOwner, solanaOwnershipChange.riskyPostOwner);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mint, symbol, postOwner, decimals, name, preOwner, ownerChanged, riskyPostOwner);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SolanaOwnershipChange {\n");
    
    sb.append("    mint: ").append(toIndentedString(mint)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    postOwner: ").append(toIndentedString(postOwner)).append("\n");
    sb.append("    decimals: ").append(toIndentedString(decimals)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    preOwner: ").append(toIndentedString(preOwner)).append("\n");
    sb.append("    ownerChanged: ").append(toIndentedString(ownerChanged)).append("\n");
    sb.append("    riskyPostOwner: ").append(toIndentedString(riskyPostOwner)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
