/*
 * GoPlus Security API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.gopluslabs.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * Token NFT Lock
 */
@Schema(description = "Token NFT Lock")


public class TaNftLockerLockInfo {
  @SerializedName("endTime")
  private Long endTime = null;

  @SerializedName("liquidity")
  private BigDecimal liquidity = null;

  @SerializedName("lockId")
  private String lockId = null;

  @SerializedName("lockedPercent")
  private String lockedPercent = null;

  @SerializedName("nftId")
  private String nftId = null;

  @SerializedName("nftPositionManager")
  private String nftPositionManager = null;

  @SerializedName("owner")
  private String owner = null;

  @SerializedName("pool")
  private String pool = null;

  @SerializedName("startTime")
  private Long startTime = null;

  public TaNftLockerLockInfo endTime(Long endTime) {
    this.endTime = endTime;
    return this;
  }

   /**
   * 解锁时间戳
   * @return endTime
  **/
  @Schema(description = "解锁时间戳")
  public Long getEndTime() {
    return endTime;
  }

  public void setEndTime(Long endTime) {
    this.endTime = endTime;
  }

  public TaNftLockerLockInfo liquidity(BigDecimal liquidity) {
    this.liquidity = liquidity;
    return this;
  }

   /**
   * liquidity
   * @return liquidity
  **/
  @Schema(description = "liquidity")
  public BigDecimal getLiquidity() {
    return liquidity;
  }

  public void setLiquidity(BigDecimal liquidity) {
    this.liquidity = liquidity;
  }

  public TaNftLockerLockInfo lockId(String lockId) {
    this.lockId = lockId;
    return this;
  }

   /**
   * lock id
   * @return lockId
  **/
  @Schema(description = "lock id")
  public String getLockId() {
    return lockId;
  }

  public void setLockId(String lockId) {
    this.lockId = lockId;
  }

  public TaNftLockerLockInfo lockedPercent(String lockedPercent) {
    this.lockedPercent = lockedPercent;
    return this;
  }

   /**
   * 锁仓比例
   * @return lockedPercent
  **/
  @Schema(description = "锁仓比例")
  public String getLockedPercent() {
    return lockedPercent;
  }

  public void setLockedPercent(String lockedPercent) {
    this.lockedPercent = lockedPercent;
  }

  public TaNftLockerLockInfo nftId(String nftId) {
    this.nftId = nftId;
    return this;
  }

   /**
   * nft id
   * @return nftId
  **/
  @Schema(description = "nft id")
  public String getNftId() {
    return nftId;
  }

  public void setNftId(String nftId) {
    this.nftId = nftId;
  }

  public TaNftLockerLockInfo nftPositionManager(String nftPositionManager) {
    this.nftPositionManager = nftPositionManager;
    return this;
  }

   /**
   * nft Position Manager
   * @return nftPositionManager
  **/
  @Schema(description = "nft Position Manager")
  public String getNftPositionManager() {
    return nftPositionManager;
  }

  public void setNftPositionManager(String nftPositionManager) {
    this.nftPositionManager = nftPositionManager;
  }

  public TaNftLockerLockInfo owner(String owner) {
    this.owner = owner;
    return this;
  }

   /**
   * user address
   * @return owner
  **/
  @Schema(description = "user address")
  public String getOwner() {
    return owner;
  }

  public void setOwner(String owner) {
    this.owner = owner;
  }

  public TaNftLockerLockInfo pool(String pool) {
    this.pool = pool;
    return this;
  }

   /**
   * pool address
   * @return pool
  **/
  @Schema(description = "pool address")
  public String getPool() {
    return pool;
  }

  public void setPool(String pool) {
    this.pool = pool;
  }

  public TaNftLockerLockInfo startTime(Long startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * 开始时间戳
   * @return startTime
  **/
  @Schema(description = "开始时间戳")
  public Long getStartTime() {
    return startTime;
  }

  public void setStartTime(Long startTime) {
    this.startTime = startTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaNftLockerLockInfo taNftLockerLockInfo = (TaNftLockerLockInfo) o;
    return Objects.equals(this.endTime, taNftLockerLockInfo.endTime) &&
        Objects.equals(this.liquidity, taNftLockerLockInfo.liquidity) &&
        Objects.equals(this.lockId, taNftLockerLockInfo.lockId) &&
        Objects.equals(this.lockedPercent, taNftLockerLockInfo.lockedPercent) &&
        Objects.equals(this.nftId, taNftLockerLockInfo.nftId) &&
        Objects.equals(this.nftPositionManager, taNftLockerLockInfo.nftPositionManager) &&
        Objects.equals(this.owner, taNftLockerLockInfo.owner) &&
        Objects.equals(this.pool, taNftLockerLockInfo.pool) &&
        Objects.equals(this.startTime, taNftLockerLockInfo.startTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(endTime, liquidity, lockId, lockedPercent, nftId, nftPositionManager, owner, pool, startTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaNftLockerLockInfo {\n");
    
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    liquidity: ").append(toIndentedString(liquidity)).append("\n");
    sb.append("    lockId: ").append(toIndentedString(lockId)).append("\n");
    sb.append("    lockedPercent: ").append(toIndentedString(lockedPercent)).append("\n");
    sb.append("    nftId: ").append(toIndentedString(nftId)).append("\n");
    sb.append("    nftPositionManager: ").append(toIndentedString(nftPositionManager)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    pool: ").append(toIndentedString(pool)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
