/*
 * GoPlus Security API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.gopluslabs.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Token Locker Lock
 */
@Schema(description = "Token Locker Lock")


public class TaTokenLockerLockInfo {
  @SerializedName("amount")
  private String amount = null;

  @SerializedName("endTime")
  private Long endTime = null;

  @SerializedName("isLpToken")
  private Integer isLpToken = null;

  @SerializedName("lockId")
  private String lockId = null;

  @SerializedName("lockedPercent")
  private String lockedPercent = null;

  @SerializedName("owner")
  private String owner = null;

  @SerializedName("startTime")
  private Long startTime = null;

  @SerializedName("token")
  private String token = null;

  @SerializedName("unlockedAmount")
  private String unlockedAmount = null;

  public TaTokenLockerLockInfo amount(String amount) {
    this.amount = amount;
    return this;
  }

   /**
   * amount
   * @return amount
  **/
  @Schema(description = "amount")
  public String getAmount() {
    return amount;
  }

  public void setAmount(String amount) {
    this.amount = amount;
  }

  public TaTokenLockerLockInfo endTime(Long endTime) {
    this.endTime = endTime;
    return this;
  }

   /**
   * endTime
   * @return endTime
  **/
  @Schema(description = "endTime")
  public Long getEndTime() {
    return endTime;
  }

  public void setEndTime(Long endTime) {
    this.endTime = endTime;
  }

  public TaTokenLockerLockInfo isLpToken(Integer isLpToken) {
    this.isLpToken = isLpToken;
    return this;
  }

   /**
   * is lp token -1:unknow,0:no,1:yes
   * @return isLpToken
  **/
  @Schema(description = "is lp token -1:unknow,0:no,1:yes")
  public Integer getIsLpToken() {
    return isLpToken;
  }

  public void setIsLpToken(Integer isLpToken) {
    this.isLpToken = isLpToken;
  }

  public TaTokenLockerLockInfo lockId(String lockId) {
    this.lockId = lockId;
    return this;
  }

   /**
   * lock id
   * @return lockId
  **/
  @Schema(description = "lock id")
  public String getLockId() {
    return lockId;
  }

  public void setLockId(String lockId) {
    this.lockId = lockId;
  }

  public TaTokenLockerLockInfo lockedPercent(String lockedPercent) {
    this.lockedPercent = lockedPercent;
    return this;
  }

   /**
   * lockedPercent
   * @return lockedPercent
  **/
  @Schema(description = "lockedPercent")
  public String getLockedPercent() {
    return lockedPercent;
  }

  public void setLockedPercent(String lockedPercent) {
    this.lockedPercent = lockedPercent;
  }

  public TaTokenLockerLockInfo owner(String owner) {
    this.owner = owner;
    return this;
  }

   /**
   * user address
   * @return owner
  **/
  @Schema(description = "user address")
  public String getOwner() {
    return owner;
  }

  public void setOwner(String owner) {
    this.owner = owner;
  }

  public TaTokenLockerLockInfo startTime(Long startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * startTime
   * @return startTime
  **/
  @Schema(description = "startTime")
  public Long getStartTime() {
    return startTime;
  }

  public void setStartTime(Long startTime) {
    this.startTime = startTime;
  }

  public TaTokenLockerLockInfo token(String token) {
    this.token = token;
    return this;
  }

   /**
   * token contract address
   * @return token
  **/
  @Schema(description = "token contract address")
  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }

  public TaTokenLockerLockInfo unlockedAmount(String unlockedAmount) {
    this.unlockedAmount = unlockedAmount;
    return this;
  }

   /**
   * unlockedAmount
   * @return unlockedAmount
  **/
  @Schema(description = "unlockedAmount")
  public String getUnlockedAmount() {
    return unlockedAmount;
  }

  public void setUnlockedAmount(String unlockedAmount) {
    this.unlockedAmount = unlockedAmount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaTokenLockerLockInfo taTokenLockerLockInfo = (TaTokenLockerLockInfo) o;
    return Objects.equals(this.amount, taTokenLockerLockInfo.amount) &&
        Objects.equals(this.endTime, taTokenLockerLockInfo.endTime) &&
        Objects.equals(this.isLpToken, taTokenLockerLockInfo.isLpToken) &&
        Objects.equals(this.lockId, taTokenLockerLockInfo.lockId) &&
        Objects.equals(this.lockedPercent, taTokenLockerLockInfo.lockedPercent) &&
        Objects.equals(this.owner, taTokenLockerLockInfo.owner) &&
        Objects.equals(this.startTime, taTokenLockerLockInfo.startTime) &&
        Objects.equals(this.token, taTokenLockerLockInfo.token) &&
        Objects.equals(this.unlockedAmount, taTokenLockerLockInfo.unlockedAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, endTime, isLpToken, lockId, lockedPercent, owner, startTime, token, unlockedAmount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaTokenLockerLockInfo {\n");
    
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    isLpToken: ").append(toIndentedString(isLpToken)).append("\n");
    sb.append("    lockId: ").append(toIndentedString(lockId)).append("\n");
    sb.append("    lockedPercent: ").append(toIndentedString(lockedPercent)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    unlockedAmount: ").append(toIndentedString(unlockedAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
