/*
 * GoPlus Security API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.gopluslabs.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gopluslabs.client.model.AddressInfo;
import io.gopluslabs.client.model.AllowanceChange;
import io.gopluslabs.client.model.ERC20BalanceChange;
import io.gopluslabs.client.model.ERC721BalanceChange;
import io.gopluslabs.client.model.Flag;
import io.gopluslabs.client.model.LogEntry;
import io.gopluslabs.client.model.NativeBalanceChange;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * TransactionSecurityResponse
 */



public class TransactionSecurityResponse {
  @SerializedName("erc20_allowance_changes")
  private List<AllowanceChange> erc20AllowanceChanges = null;

  @SerializedName("erc20_balance_changes")
  private List<ERC20BalanceChange> erc20BalanceChanges = null;

  @SerializedName("erc721_balance_changes")
  private List<ERC721BalanceChange> erc721BalanceChanges = null;

  @SerializedName("flagged")
  private List<Flag> flagged = null;

  @SerializedName("is_revert")
  private Boolean isRevert = null;

  @SerializedName("is_simulated")
  private Boolean isSimulated = null;

  @SerializedName("logs")
  private List<LogEntry> logs = null;

  @SerializedName("native_balance_changes")
  private List<NativeBalanceChange> nativeBalanceChanges = null;

  @SerializedName("revert_reason")
  private String revertReason = null;

  @SerializedName("simulate_failed_reason")
  private String simulateFailedReason = null;

  @SerializedName("suspicious_addresses")
  private List<AddressInfo> suspiciousAddresses = null;

  @SerializedName("suspicious_url")
  private Boolean suspiciousUrl = null;

  @SerializedName("used_gas")
  private Long usedGas = null;

  public TransactionSecurityResponse erc20AllowanceChanges(List<AllowanceChange> erc20AllowanceChanges) {
    this.erc20AllowanceChanges = erc20AllowanceChanges;
    return this;
  }

  public TransactionSecurityResponse addErc20AllowanceChangesItem(AllowanceChange erc20AllowanceChangesItem) {
    if (this.erc20AllowanceChanges == null) {
      this.erc20AllowanceChanges = new ArrayList<AllowanceChange>();
    }
    this.erc20AllowanceChanges.add(erc20AllowanceChangesItem);
    return this;
  }

   /**
   * Get erc20AllowanceChanges
   * @return erc20AllowanceChanges
  **/
  @Schema(description = "")
  public List<AllowanceChange> getErc20AllowanceChanges() {
    return erc20AllowanceChanges;
  }

  public void setErc20AllowanceChanges(List<AllowanceChange> erc20AllowanceChanges) {
    this.erc20AllowanceChanges = erc20AllowanceChanges;
  }

  public TransactionSecurityResponse erc20BalanceChanges(List<ERC20BalanceChange> erc20BalanceChanges) {
    this.erc20BalanceChanges = erc20BalanceChanges;
    return this;
  }

  public TransactionSecurityResponse addErc20BalanceChangesItem(ERC20BalanceChange erc20BalanceChangesItem) {
    if (this.erc20BalanceChanges == null) {
      this.erc20BalanceChanges = new ArrayList<ERC20BalanceChange>();
    }
    this.erc20BalanceChanges.add(erc20BalanceChangesItem);
    return this;
  }

   /**
   * Get erc20BalanceChanges
   * @return erc20BalanceChanges
  **/
  @Schema(description = "")
  public List<ERC20BalanceChange> getErc20BalanceChanges() {
    return erc20BalanceChanges;
  }

  public void setErc20BalanceChanges(List<ERC20BalanceChange> erc20BalanceChanges) {
    this.erc20BalanceChanges = erc20BalanceChanges;
  }

  public TransactionSecurityResponse erc721BalanceChanges(List<ERC721BalanceChange> erc721BalanceChanges) {
    this.erc721BalanceChanges = erc721BalanceChanges;
    return this;
  }

  public TransactionSecurityResponse addErc721BalanceChangesItem(ERC721BalanceChange erc721BalanceChangesItem) {
    if (this.erc721BalanceChanges == null) {
      this.erc721BalanceChanges = new ArrayList<ERC721BalanceChange>();
    }
    this.erc721BalanceChanges.add(erc721BalanceChangesItem);
    return this;
  }

   /**
   * Get erc721BalanceChanges
   * @return erc721BalanceChanges
  **/
  @Schema(description = "")
  public List<ERC721BalanceChange> getErc721BalanceChanges() {
    return erc721BalanceChanges;
  }

  public void setErc721BalanceChanges(List<ERC721BalanceChange> erc721BalanceChanges) {
    this.erc721BalanceChanges = erc721BalanceChanges;
  }

  public TransactionSecurityResponse flagged(List<Flag> flagged) {
    this.flagged = flagged;
    return this;
  }

  public TransactionSecurityResponse addFlaggedItem(Flag flaggedItem) {
    if (this.flagged == null) {
      this.flagged = new ArrayList<Flag>();
    }
    this.flagged.add(flaggedItem);
    return this;
  }

   /**
   * Get flagged
   * @return flagged
  **/
  @Schema(description = "")
  public List<Flag> getFlagged() {
    return flagged;
  }

  public void setFlagged(List<Flag> flagged) {
    this.flagged = flagged;
  }

  public TransactionSecurityResponse isRevert(Boolean isRevert) {
    this.isRevert = isRevert;
    return this;
  }

   /**
   * Get isRevert
   * @return isRevert
  **/
  @Schema(description = "")
  public Boolean isIsRevert() {
    return isRevert;
  }

  public void setIsRevert(Boolean isRevert) {
    this.isRevert = isRevert;
  }

  public TransactionSecurityResponse isSimulated(Boolean isSimulated) {
    this.isSimulated = isSimulated;
    return this;
  }

   /**
   * Get isSimulated
   * @return isSimulated
  **/
  @Schema(description = "")
  public Boolean isIsSimulated() {
    return isSimulated;
  }

  public void setIsSimulated(Boolean isSimulated) {
    this.isSimulated = isSimulated;
  }

  public TransactionSecurityResponse logs(List<LogEntry> logs) {
    this.logs = logs;
    return this;
  }

  public TransactionSecurityResponse addLogsItem(LogEntry logsItem) {
    if (this.logs == null) {
      this.logs = new ArrayList<LogEntry>();
    }
    this.logs.add(logsItem);
    return this;
  }

   /**
   * Get logs
   * @return logs
  **/
  @Schema(description = "")
  public List<LogEntry> getLogs() {
    return logs;
  }

  public void setLogs(List<LogEntry> logs) {
    this.logs = logs;
  }

  public TransactionSecurityResponse nativeBalanceChanges(List<NativeBalanceChange> nativeBalanceChanges) {
    this.nativeBalanceChanges = nativeBalanceChanges;
    return this;
  }

  public TransactionSecurityResponse addNativeBalanceChangesItem(NativeBalanceChange nativeBalanceChangesItem) {
    if (this.nativeBalanceChanges == null) {
      this.nativeBalanceChanges = new ArrayList<NativeBalanceChange>();
    }
    this.nativeBalanceChanges.add(nativeBalanceChangesItem);
    return this;
  }

   /**
   * Get nativeBalanceChanges
   * @return nativeBalanceChanges
  **/
  @Schema(description = "")
  public List<NativeBalanceChange> getNativeBalanceChanges() {
    return nativeBalanceChanges;
  }

  public void setNativeBalanceChanges(List<NativeBalanceChange> nativeBalanceChanges) {
    this.nativeBalanceChanges = nativeBalanceChanges;
  }

  public TransactionSecurityResponse revertReason(String revertReason) {
    this.revertReason = revertReason;
    return this;
  }

   /**
   * Get revertReason
   * @return revertReason
  **/
  @Schema(description = "")
  public String getRevertReason() {
    return revertReason;
  }

  public void setRevertReason(String revertReason) {
    this.revertReason = revertReason;
  }

  public TransactionSecurityResponse simulateFailedReason(String simulateFailedReason) {
    this.simulateFailedReason = simulateFailedReason;
    return this;
  }

   /**
   * Get simulateFailedReason
   * @return simulateFailedReason
  **/
  @Schema(description = "")
  public String getSimulateFailedReason() {
    return simulateFailedReason;
  }

  public void setSimulateFailedReason(String simulateFailedReason) {
    this.simulateFailedReason = simulateFailedReason;
  }

  public TransactionSecurityResponse suspiciousAddresses(List<AddressInfo> suspiciousAddresses) {
    this.suspiciousAddresses = suspiciousAddresses;
    return this;
  }

  public TransactionSecurityResponse addSuspiciousAddressesItem(AddressInfo suspiciousAddressesItem) {
    if (this.suspiciousAddresses == null) {
      this.suspiciousAddresses = new ArrayList<AddressInfo>();
    }
    this.suspiciousAddresses.add(suspiciousAddressesItem);
    return this;
  }

   /**
   * Get suspiciousAddresses
   * @return suspiciousAddresses
  **/
  @Schema(description = "")
  public List<AddressInfo> getSuspiciousAddresses() {
    return suspiciousAddresses;
  }

  public void setSuspiciousAddresses(List<AddressInfo> suspiciousAddresses) {
    this.suspiciousAddresses = suspiciousAddresses;
  }

  public TransactionSecurityResponse suspiciousUrl(Boolean suspiciousUrl) {
    this.suspiciousUrl = suspiciousUrl;
    return this;
  }

   /**
   * Get suspiciousUrl
   * @return suspiciousUrl
  **/
  @Schema(description = "")
  public Boolean isSuspiciousUrl() {
    return suspiciousUrl;
  }

  public void setSuspiciousUrl(Boolean suspiciousUrl) {
    this.suspiciousUrl = suspiciousUrl;
  }

  public TransactionSecurityResponse usedGas(Long usedGas) {
    this.usedGas = usedGas;
    return this;
  }

   /**
   * Get usedGas
   * @return usedGas
  **/
  @Schema(description = "")
  public Long getUsedGas() {
    return usedGas;
  }

  public void setUsedGas(Long usedGas) {
    this.usedGas = usedGas;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionSecurityResponse transactionSecurityResponse = (TransactionSecurityResponse) o;
    return Objects.equals(this.erc20AllowanceChanges, transactionSecurityResponse.erc20AllowanceChanges) &&
        Objects.equals(this.erc20BalanceChanges, transactionSecurityResponse.erc20BalanceChanges) &&
        Objects.equals(this.erc721BalanceChanges, transactionSecurityResponse.erc721BalanceChanges) &&
        Objects.equals(this.flagged, transactionSecurityResponse.flagged) &&
        Objects.equals(this.isRevert, transactionSecurityResponse.isRevert) &&
        Objects.equals(this.isSimulated, transactionSecurityResponse.isSimulated) &&
        Objects.equals(this.logs, transactionSecurityResponse.logs) &&
        Objects.equals(this.nativeBalanceChanges, transactionSecurityResponse.nativeBalanceChanges) &&
        Objects.equals(this.revertReason, transactionSecurityResponse.revertReason) &&
        Objects.equals(this.simulateFailedReason, transactionSecurityResponse.simulateFailedReason) &&
        Objects.equals(this.suspiciousAddresses, transactionSecurityResponse.suspiciousAddresses) &&
        Objects.equals(this.suspiciousUrl, transactionSecurityResponse.suspiciousUrl) &&
        Objects.equals(this.usedGas, transactionSecurityResponse.usedGas);
  }

  @Override
  public int hashCode() {
    return Objects.hash(erc20AllowanceChanges, erc20BalanceChanges, erc721BalanceChanges, flagged, isRevert, isSimulated, logs, nativeBalanceChanges, revertReason, simulateFailedReason, suspiciousAddresses, suspiciousUrl, usedGas);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionSecurityResponse {\n");
    
    sb.append("    erc20AllowanceChanges: ").append(toIndentedString(erc20AllowanceChanges)).append("\n");
    sb.append("    erc20BalanceChanges: ").append(toIndentedString(erc20BalanceChanges)).append("\n");
    sb.append("    erc721BalanceChanges: ").append(toIndentedString(erc721BalanceChanges)).append("\n");
    sb.append("    flagged: ").append(toIndentedString(flagged)).append("\n");
    sb.append("    isRevert: ").append(toIndentedString(isRevert)).append("\n");
    sb.append("    isSimulated: ").append(toIndentedString(isSimulated)).append("\n");
    sb.append("    logs: ").append(toIndentedString(logs)).append("\n");
    sb.append("    nativeBalanceChanges: ").append(toIndentedString(nativeBalanceChanges)).append("\n");
    sb.append("    revertReason: ").append(toIndentedString(revertReason)).append("\n");
    sb.append("    simulateFailedReason: ").append(toIndentedString(simulateFailedReason)).append("\n");
    sb.append("    suspiciousAddresses: ").append(toIndentedString(suspiciousAddresses)).append("\n");
    sb.append("    suspiciousUrl: ").append(toIndentedString(suspiciousUrl)).append("\n");
    sb.append("    usedGas: ").append(toIndentedString(usedGas)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
