/*
 * GoPlus Security API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.gopluslabs.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gopluslabs.client.model.AddressInfo;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * TransactionSecurityRequest
 */



public class TransactionSecurityRequest {
  @SerializedName("access_list")
  private List<AddressInfo> accessList = null;

  @SerializedName("chain_id")
  private String chainId = null;

  @SerializedName("data")
  private String data = null;

  @SerializedName("from")
  private String from = null;

  @SerializedName("gas_limit")
  private String gasLimit = null;

  @SerializedName("gas_price")
  private String gasPrice = null;

  @SerializedName("max_fee_per_gas")
  private String maxFeePerGas = null;

  @SerializedName("max_priority_fee_per_gas")
  private String maxPriorityFeePerGas = null;

  @SerializedName("nonce")
  private String nonce = null;

  @SerializedName("to")
  private String to = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("value")
  private String value = null;

  public TransactionSecurityRequest accessList(List<AddressInfo> accessList) {
    this.accessList = accessList;
    return this;
  }

  public TransactionSecurityRequest addAccessListItem(AddressInfo accessListItem) {
    if (this.accessList == null) {
      this.accessList = new ArrayList<AddressInfo>();
    }
    this.accessList.add(accessListItem);
    return this;
  }

   /**
   * Get accessList
   * @return accessList
  **/
  @Schema(description = "")
  public List<AddressInfo> getAccessList() {
    return accessList;
  }

  public void setAccessList(List<AddressInfo> accessList) {
    this.accessList = accessList;
  }

  public TransactionSecurityRequest chainId(String chainId) {
    this.chainId = chainId;
    return this;
  }

   /**
   * Get chainId
   * @return chainId
  **/
  @Schema(description = "")
  public String getChainId() {
    return chainId;
  }

  public void setChainId(String chainId) {
    this.chainId = chainId;
  }

  public TransactionSecurityRequest data(String data) {
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @Schema(description = "")
  public String getData() {
    return data;
  }

  public void setData(String data) {
    this.data = data;
  }

  public TransactionSecurityRequest from(String from) {
    this.from = from;
    return this;
  }

   /**
   * Get from
   * @return from
  **/
  @Schema(description = "")
  public String getFrom() {
    return from;
  }

  public void setFrom(String from) {
    this.from = from;
  }

  public TransactionSecurityRequest gasLimit(String gasLimit) {
    this.gasLimit = gasLimit;
    return this;
  }

   /**
   * Get gasLimit
   * @return gasLimit
  **/
  @Schema(description = "")
  public String getGasLimit() {
    return gasLimit;
  }

  public void setGasLimit(String gasLimit) {
    this.gasLimit = gasLimit;
  }

  public TransactionSecurityRequest gasPrice(String gasPrice) {
    this.gasPrice = gasPrice;
    return this;
  }

   /**
   * Get gasPrice
   * @return gasPrice
  **/
  @Schema(description = "")
  public String getGasPrice() {
    return gasPrice;
  }

  public void setGasPrice(String gasPrice) {
    this.gasPrice = gasPrice;
  }

  public TransactionSecurityRequest maxFeePerGas(String maxFeePerGas) {
    this.maxFeePerGas = maxFeePerGas;
    return this;
  }

   /**
   * Get maxFeePerGas
   * @return maxFeePerGas
  **/
  @Schema(description = "")
  public String getMaxFeePerGas() {
    return maxFeePerGas;
  }

  public void setMaxFeePerGas(String maxFeePerGas) {
    this.maxFeePerGas = maxFeePerGas;
  }

  public TransactionSecurityRequest maxPriorityFeePerGas(String maxPriorityFeePerGas) {
    this.maxPriorityFeePerGas = maxPriorityFeePerGas;
    return this;
  }

   /**
   * Get maxPriorityFeePerGas
   * @return maxPriorityFeePerGas
  **/
  @Schema(description = "")
  public String getMaxPriorityFeePerGas() {
    return maxPriorityFeePerGas;
  }

  public void setMaxPriorityFeePerGas(String maxPriorityFeePerGas) {
    this.maxPriorityFeePerGas = maxPriorityFeePerGas;
  }

  public TransactionSecurityRequest nonce(String nonce) {
    this.nonce = nonce;
    return this;
  }

   /**
   * Get nonce
   * @return nonce
  **/
  @Schema(description = "")
  public String getNonce() {
    return nonce;
  }

  public void setNonce(String nonce) {
    this.nonce = nonce;
  }

  public TransactionSecurityRequest to(String to) {
    this.to = to;
    return this;
  }

   /**
   * Get to
   * @return to
  **/
  @Schema(description = "")
  public String getTo() {
    return to;
  }

  public void setTo(String to) {
    this.to = to;
  }

  public TransactionSecurityRequest url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @Schema(description = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public TransactionSecurityRequest value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @Schema(description = "")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionSecurityRequest transactionSecurityRequest = (TransactionSecurityRequest) o;
    return Objects.equals(this.accessList, transactionSecurityRequest.accessList) &&
        Objects.equals(this.chainId, transactionSecurityRequest.chainId) &&
        Objects.equals(this.data, transactionSecurityRequest.data) &&
        Objects.equals(this.from, transactionSecurityRequest.from) &&
        Objects.equals(this.gasLimit, transactionSecurityRequest.gasLimit) &&
        Objects.equals(this.gasPrice, transactionSecurityRequest.gasPrice) &&
        Objects.equals(this.maxFeePerGas, transactionSecurityRequest.maxFeePerGas) &&
        Objects.equals(this.maxPriorityFeePerGas, transactionSecurityRequest.maxPriorityFeePerGas) &&
        Objects.equals(this.nonce, transactionSecurityRequest.nonce) &&
        Objects.equals(this.to, transactionSecurityRequest.to) &&
        Objects.equals(this.url, transactionSecurityRequest.url) &&
        Objects.equals(this.value, transactionSecurityRequest.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessList, chainId, data, from, gasLimit, gasPrice, maxFeePerGas, maxPriorityFeePerGas, nonce, to, url, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionSecurityRequest {\n");
    
    sb.append("    accessList: ").append(toIndentedString(accessList)).append("\n");
    sb.append("    chainId: ").append(toIndentedString(chainId)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    gasLimit: ").append(toIndentedString(gasLimit)).append("\n");
    sb.append("    gasPrice: ").append(toIndentedString(gasPrice)).append("\n");
    sb.append("    maxFeePerGas: ").append(toIndentedString(maxFeePerGas)).append("\n");
    sb.append("    maxPriorityFeePerGas: ").append(toIndentedString(maxPriorityFeePerGas)).append("\n");
    sb.append("    nonce: ").append(toIndentedString(nonce)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
