/*
 * GoPlus Security API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.gopluslabs.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * V4LpLockerLockInfoResp
 */



public class V4LpLockerLockInfoResp {
  @SerializedName("endTime")
  private Long endTime = null;

  @SerializedName("lockId")
  private String lockId = null;

  @SerializedName("nftId")
  private String nftId = null;

  @SerializedName("nftPositionManager")
  private String nftPositionManager = null;

  @SerializedName("owner")
  private String owner = null;

  @SerializedName("poolId")
  private String poolId = null;

  @SerializedName("startTime")
  private Long startTime = null;

  public V4LpLockerLockInfoResp endTime(Long endTime) {
    this.endTime = endTime;
    return this;
  }

   /**
   * 解锁时间戳
   * @return endTime
  **/
  @Schema(description = "解锁时间戳")
  public Long getEndTime() {
    return endTime;
  }

  public void setEndTime(Long endTime) {
    this.endTime = endTime;
  }

  public V4LpLockerLockInfoResp lockId(String lockId) {
    this.lockId = lockId;
    return this;
  }

   /**
   * lock id
   * @return lockId
  **/
  @Schema(description = "lock id")
  public String getLockId() {
    return lockId;
  }

  public void setLockId(String lockId) {
    this.lockId = lockId;
  }

  public V4LpLockerLockInfoResp nftId(String nftId) {
    this.nftId = nftId;
    return this;
  }

   /**
   * nft id
   * @return nftId
  **/
  @Schema(description = "nft id")
  public String getNftId() {
    return nftId;
  }

  public void setNftId(String nftId) {
    this.nftId = nftId;
  }

  public V4LpLockerLockInfoResp nftPositionManager(String nftPositionManager) {
    this.nftPositionManager = nftPositionManager;
    return this;
  }

   /**
   * nft Position Manager
   * @return nftPositionManager
  **/
  @Schema(description = "nft Position Manager")
  public String getNftPositionManager() {
    return nftPositionManager;
  }

  public void setNftPositionManager(String nftPositionManager) {
    this.nftPositionManager = nftPositionManager;
  }

  public V4LpLockerLockInfoResp owner(String owner) {
    this.owner = owner;
    return this;
  }

   /**
   * user address
   * @return owner
  **/
  @Schema(description = "user address")
  public String getOwner() {
    return owner;
  }

  public void setOwner(String owner) {
    this.owner = owner;
  }

  public V4LpLockerLockInfoResp poolId(String poolId) {
    this.poolId = poolId;
    return this;
  }

   /**
   * pool id
   * @return poolId
  **/
  @Schema(description = "pool id")
  public String getPoolId() {
    return poolId;
  }

  public void setPoolId(String poolId) {
    this.poolId = poolId;
  }

  public V4LpLockerLockInfoResp startTime(Long startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * 开始时间戳
   * @return startTime
  **/
  @Schema(description = "开始时间戳")
  public Long getStartTime() {
    return startTime;
  }

  public void setStartTime(Long startTime) {
    this.startTime = startTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V4LpLockerLockInfoResp v4LpLockerLockInfoResp = (V4LpLockerLockInfoResp) o;
    return Objects.equals(this.endTime, v4LpLockerLockInfoResp.endTime) &&
        Objects.equals(this.lockId, v4LpLockerLockInfoResp.lockId) &&
        Objects.equals(this.nftId, v4LpLockerLockInfoResp.nftId) &&
        Objects.equals(this.nftPositionManager, v4LpLockerLockInfoResp.nftPositionManager) &&
        Objects.equals(this.owner, v4LpLockerLockInfoResp.owner) &&
        Objects.equals(this.poolId, v4LpLockerLockInfoResp.poolId) &&
        Objects.equals(this.startTime, v4LpLockerLockInfoResp.startTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(endTime, lockId, nftId, nftPositionManager, owner, poolId, startTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V4LpLockerLockInfoResp {\n");
    
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    lockId: ").append(toIndentedString(lockId)).append("\n");
    sb.append("    nftId: ").append(toIndentedString(nftId)).append("\n");
    sb.append("    nftPositionManager: ").append(toIndentedString(nftPositionManager)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    poolId: ").append(toIndentedString(poolId)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
