/*
 * GoPlus Security API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.gopluslabs.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gopluslabs.client.model.TaNftLockerLockInfo;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * V4 Token NFT Lock
 */
@Schema(description = "V4 Token NFT Lock")


public class V4NftLockerLockInfos {
  @SerializedName("chainId")
  private String chainId = null;

  @SerializedName("lockList")
  private List<TaNftLockerLockInfo> lockList = null;

  @SerializedName("nftPositionManager")
  private String nftPositionManager = null;

  @SerializedName("poolId")
  private String poolId = null;

  @SerializedName("url")
  private String url = null;

  public V4NftLockerLockInfos chainId(String chainId) {
    this.chainId = chainId;
    return this;
  }

   /**
   * chain id
   * @return chainId
  **/
  @Schema(description = "chain id")
  public String getChainId() {
    return chainId;
  }

  public void setChainId(String chainId) {
    this.chainId = chainId;
  }

  public V4NftLockerLockInfos lockList(List<TaNftLockerLockInfo> lockList) {
    this.lockList = lockList;
    return this;
  }

  public V4NftLockerLockInfos addLockListItem(TaNftLockerLockInfo lockListItem) {
    if (this.lockList == null) {
      this.lockList = new ArrayList<TaNftLockerLockInfo>();
    }
    this.lockList.add(lockListItem);
    return this;
  }

   /**
   * lock info list
   * @return lockList
  **/
  @Schema(description = "lock info list")
  public List<TaNftLockerLockInfo> getLockList() {
    return lockList;
  }

  public void setLockList(List<TaNftLockerLockInfo> lockList) {
    this.lockList = lockList;
  }

  public V4NftLockerLockInfos nftPositionManager(String nftPositionManager) {
    this.nftPositionManager = nftPositionManager;
    return this;
  }

   /**
   * nft Position Manager
   * @return nftPositionManager
  **/
  @Schema(description = "nft Position Manager")
  public String getNftPositionManager() {
    return nftPositionManager;
  }

  public void setNftPositionManager(String nftPositionManager) {
    this.nftPositionManager = nftPositionManager;
  }

  public V4NftLockerLockInfos poolId(String poolId) {
    this.poolId = poolId;
    return this;
  }

   /**
   * pool id
   * @return poolId
  **/
  @Schema(description = "pool id")
  public String getPoolId() {
    return poolId;
  }

  public void setPoolId(String poolId) {
    this.poolId = poolId;
  }

  public V4NftLockerLockInfos url(String url) {
    this.url = url;
    return this;
  }

   /**
   * url
   * @return url
  **/
  @Schema(description = "url")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V4NftLockerLockInfos v4NftLockerLockInfos = (V4NftLockerLockInfos) o;
    return Objects.equals(this.chainId, v4NftLockerLockInfos.chainId) &&
        Objects.equals(this.lockList, v4NftLockerLockInfos.lockList) &&
        Objects.equals(this.nftPositionManager, v4NftLockerLockInfos.nftPositionManager) &&
        Objects.equals(this.poolId, v4NftLockerLockInfos.poolId) &&
        Objects.equals(this.url, v4NftLockerLockInfos.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chainId, lockList, nftPositionManager, poolId, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V4NftLockerLockInfos {\n");
    
    sb.append("    chainId: ").append(toIndentedString(chainId)).append("\n");
    sb.append("    lockList: ").append(toIndentedString(lockList)).append("\n");
    sb.append("    nftPositionManager: ").append(toIndentedString(nftPositionManager)).append("\n");
    sb.append("    poolId: ").append(toIndentedString(poolId)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
