/*
 * GoPlus Security API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ResponseWrapperListJSONObject9524a1c652c545bfb6c6898bfc3e93f3Result;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * ResponseWrapperListJSONObject9524a1c652c545bfB6c6898bfc3e93f3
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-05-08T09:37:56.615797436Z[Etc/UTC]")
public class ResponseWrapperListJSONObject9524a1c652c545bfB6c6898bfc3e93f3 {
  @SerializedName("code")
  private Integer code = null;

  @SerializedName("message")
  private String message = null;

  @SerializedName("result")
  private List<ResponseWrapperListJSONObject9524a1c652c545bfb6c6898bfc3e93f3Result> result = null;

  public ResponseWrapperListJSONObject9524a1c652c545bfB6c6898bfc3e93f3 code(Integer code) {
    this.code = code;
    return this;
  }

   /**
   * Code 1：Success
   * @return code
  **/
  @Schema(description = "Code 1：Success")
  public Integer getCode() {
    return code;
  }

  public void setCode(Integer code) {
    this.code = code;
  }

  public ResponseWrapperListJSONObject9524a1c652c545bfB6c6898bfc3e93f3 message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Response message
   * @return message
  **/
  @Schema(description = "Response message")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public ResponseWrapperListJSONObject9524a1c652c545bfB6c6898bfc3e93f3 result(List<ResponseWrapperListJSONObject9524a1c652c545bfb6c6898bfc3e93f3Result> result) {
    this.result = result;
    return this;
  }

  public ResponseWrapperListJSONObject9524a1c652c545bfB6c6898bfc3e93f3 addResultItem(ResponseWrapperListJSONObject9524a1c652c545bfb6c6898bfc3e93f3Result resultItem) {
    if (this.result == null) {
      this.result = new ArrayList<ResponseWrapperListJSONObject9524a1c652c545bfb6c6898bfc3e93f3Result>();
    }
    this.result.add(resultItem);
    return this;
  }

   /**
   * Response result
   * @return result
  **/
  @Schema(description = "Response result")
  public List<ResponseWrapperListJSONObject9524a1c652c545bfb6c6898bfc3e93f3Result> getResult() {
    return result;
  }

  public void setResult(List<ResponseWrapperListJSONObject9524a1c652c545bfb6c6898bfc3e93f3Result> result) {
    this.result = result;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseWrapperListJSONObject9524a1c652c545bfB6c6898bfc3e93f3 responseWrapperListJSONObject9524a1c652c545bfB6c6898bfc3e93f3 = (ResponseWrapperListJSONObject9524a1c652c545bfB6c6898bfc3e93f3) o;
    return Objects.equals(this.code, responseWrapperListJSONObject9524a1c652c545bfB6c6898bfc3e93f3.code) &&
        Objects.equals(this.message, responseWrapperListJSONObject9524a1c652c545bfB6c6898bfc3e93f3.message) &&
        Objects.equals(this.result, responseWrapperListJSONObject9524a1c652c545bfB6c6898bfc3e93f3.result);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, message, result);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseWrapperListJSONObject9524a1c652c545bfB6c6898bfc3e93f3 {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
